truncate table Valid.CollectionDetails
truncate table Valid.[Source]
truncate table Valid.SourceFile
truncate table Valid.LearningProvider
truncate table Valid.Learner
truncate table Valid.LearnerDenormTbl
truncate table Valid.ContactPreference
truncate table Valid.LLDDandHealthProblem
truncate table Valid.LearnerFAM
truncate table Valid.ProviderSpecLearnerMonitoring
truncate table Valid.LearnerEmploymentStatus
truncate table Valid.LearnerEmploymentStatusDenormTbl
truncate table Valid.EmploymentStatusMonitoring
truncate table Valid.LearnerHE
truncate table Valid.LearnerHEFinancialSupport
truncate table Valid.LearningDelivery
truncate table Valid.LearningDeliveryDenormTbl
truncate table Valid.LearningDeliveryFAM
truncate table Valid.LearningDeliveryWorkPlacement
truncate table Valid.AppFinRecord
truncate table Valid.ProviderSpecDeliveryMonitoring
truncate table Valid.LearningDeliveryHE
truncate table Valid.LearnerDestinationandProgression
truncate table Valid.DPOutcome
truncate table Valid.[File]