IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Report].[AppsIndicativeEarningsReportGetData]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [Report].[AppsIndicativeEarningsReportGetData]
GO

CREATE PROCEDURE [Report].[AppsIndicativeEarningsReportGetData]	
	@Page INT,
	@PageSize INT
AS
BEGIN

	SELECT 
	  [Learner reference number]
		   ,[Unique learner number]
		   ,[Date of birth] 
		   ,[Postcode prior to enrolment]  
		   ,[Provider specified learner monitoring (A)] 
		   ,[Provider specified learner monitoring (B)] 
		   ,[Aim sequence number]
		   ,[Learning aim reference]
		   ,[Learning aim title] 
		   ,[Software supplier aim identifier] 
		   ,[LARS 16-18 additional payments - employer] 
		   ,[LARS 16-18 additional payments - provider] 
		   ,[LARS 16-18 framework uplift]				
		   ,[Notional NVQ level] 
		   ,[Standard notional end level]
		   ,[Tier 2 sector subject area] 
           ,[Programme type]
           ,[Standard code]
           ,[Framework code]
           ,[Apprenticeship pathway]
           ,[Aim type]
           ,[Common component code]
           ,[Funding model]
           ,[Original learning start date]
           ,[Learning start date]
           ,[Learning planned end date]
           ,[Completion status]
           ,[Learning actual end date]
           ,[Outcome]
           ,[Learning delivery funding and monitoring type – source of funding]
           ,[Learning delivery funding and monitoring type – learning support funding (highest applicable)]
           ,[Learning delivery funding and monitoring type - LSF date applies from (earliest)]
           ,[Learning delivery funding and monitoring type - LSF date applies to (latest)]
           ,[Learning delivery funding and monitoring type – learning delivery monitoring (A)]
           ,[Learning delivery funding and monitoring type – learning delivery monitoring (B)]
           ,[Learning delivery funding and monitoring type – learning delivery monitoring (C)]
           ,[Learning delivery funding and monitoring type – learning delivery monitoring (D)]
           ,[Learning delivery funding and monitoring type – restart indicator]
           ,[Provider specified delivery monitoring (A)]
           ,[Provider specified delivery monitoring (B)]
           ,[Provider specified delivery monitoring (C)]
           ,[Provider specified delivery monitoring (D)]
		   ,[Endpoint assessment organisation]
           ,[Planned number of on programme instalments for aim]
           ,[Sub contracted or partnership UKPRN]
           ,[Delivery location postcode]
           ,[Employer identifier]           
           ,[Employment status]
           ,[Employment status date]
           ,[Employment status monitoring - small employer]
		   ,[Price episode start date] 
		   ,[Price episode actual end date]
		   ,[Funding line type]
		   ,[Total price applicable to this episode]	   
		   ,[Funding band upper limit]
		   ,[Price amount above funding band limit] 
		   ,[Price amount remaining (with upper limit applied) at start of this episode]
		   ,[Completion element (potential or actual earned cash)]
		   ,[Total employer contribution collected (PMR) in previous funding years]
		   ,[Total employer contribution collected (PMR) in this funding year]
		   ,[Learning delivery funding and monitoring type – apprenticeship contract type ]
		   ,[Learning delivery funding and monitoring type – ACT date applies from]
		   ,[Learning delivery funding and monitoring type – ACT date applies to]
           ,[August on programme earned cash]
           ,[August balancing payment earned cash]
           ,[August aim completion earned cash]
           ,[August total training and assessment earned]      
           ,[August learning support earned cash]
		   ,[August English and maths on programme earned cash]
           ,[August English and maths balancing payment earned cash]
		   ,[August disadvantage earned cash]
		   ,[August 16-18 additional payments for employers]
		   ,[August 16-18 additional payments for providers]
		   ,[August 16-18 framework uplift on programme payment]
		   ,[August 16-18 framework uplift balancing payment] 
		   ,[August 16-18 framework uplift completion payment]
           ,[September on programme earned cash]
           ,[September balancing payment earned cash]
           ,[September aim completion earned cash]
           ,[September total training and assessment earned]      
           ,[September learning support earned cash]
		   ,[September English and maths on programme earned cash]
           ,[September English and maths balancing payment earned cash]
		   ,[September disadvantage earned cash]
		   ,[September 16-18 additional payments for employers]
		   ,[September 16-18 additional payments for providers]
		   ,[September 16-18 framework uplift on programme payment]
		   ,[September 16-18 framework uplift balancing payment] 
		   ,[September 16-18 framework uplift completion payment]
		   ,[October on programme earned cash]
           ,[October balancing payment earned cash]
           ,[October aim completion earned cash]
           ,[October total training and assessment earned]      
           ,[October learning support earned cash]
		   ,[October English and maths on programme earned cash]
           ,[October English and maths balancing payment earned cash]
		   ,[October disadvantage earned cash]
		   ,[October 16-18 additional payments for employers]
		   ,[October 16-18 additional payments for providers]
		   ,[October 16-18 framework uplift on programme payment]
		   ,[October 16-18 framework uplift balancing payment] 
		   ,[October 16-18 framework uplift completion payment]
           ,[November on programme earned cash]
           ,[November balancing payment earned cash]
           ,[November aim completion earned cash]
           ,[November total training and assessment earned]      
           ,[November learning support earned cash]
		   ,[November English and maths on programme earned cash]
           ,[November English and maths balancing payment earned cash]
		   ,[November disadvantage earned cash]
		   ,[November 16-18 additional payments for employers]
		   ,[November 16-18 additional payments for providers]
		   ,[November 16-18 framework uplift on programme payment]
		   ,[November 16-18 framework uplift balancing payment] 
		   ,[November 16-18 framework uplift completion payment]
           ,[December on programme earned cash]
           ,[December balancing payment earned cash]
           ,[December aim completion earned cash]
           ,[December total training and assessment earned]      
           ,[December learning support earned cash]
		   ,[December English and maths on programme earned cash]
           ,[December English and maths balancing payment earned cash]
		   ,[December disadvantage earned cash]
		   ,[December 16-18 additional payments for employers]
		   ,[December 16-18 additional payments for providers]
		   ,[December 16-18 framework uplift on programme payment]
		   ,[December 16-18 framework uplift balancing payment] 
		   ,[December 16-18 framework uplift completion payment]
		   ,[January on programme earned cash]
           ,[January balancing payment earned cash]
           ,[January aim completion earned cash]
           ,[January total training and assessment earned]      
           ,[January learning support earned cash]
		   ,[January English and maths on programme earned cash]
           ,[January English and maths balancing payment earned cash]
		   ,[January disadvantage earned cash]
		   ,[January 16-18 additional payments for employers]
		   ,[January 16-18 additional payments for providers]
		   ,[January 16-18 framework uplift on programme payment]
		   ,[January 16-18 framework uplift balancing payment] 
		   ,[January 16-18 framework uplift completion payment]
           ,[February on programme earned cash]
           ,[February balancing payment earned cash]
           ,[February aim completion earned cash]
           ,[February total training and assessment earned]      
           ,[February learning support earned cash]
		   ,[February English and maths on programme earned cash]
           ,[February English and maths balancing payment earned cash]
		   ,[February disadvantage earned cash]
		   ,[February 16-18 additional payments for employers]
		   ,[February 16-18 additional payments for providers]
		   ,[February 16-18 framework uplift on programme payment]
		   ,[February 16-18 framework uplift balancing payment] 
		   ,[February 16-18 framework uplift completion payment]
           ,[March on programme earned cash]
           ,[March balancing payment earned cash]
           ,[March aim completion earned cash]
           ,[March total training and assessment earned]      
           ,[March learning support earned cash]
		   ,[March English and maths on programme earned cash]
           ,[March English and maths balancing payment earned cash]
		   ,[March disadvantage earned cash]
		   ,[March 16-18 additional payments for employers]
		   ,[March 16-18 additional payments for providers]
		   ,[March 16-18 framework uplift on programme payment]
		   ,[March 16-18 framework uplift balancing payment] 
		   ,[March 16-18 framework uplift completion payment]
           ,[April on programme earned cash]
           ,[April balancing payment earned cash]
           ,[April aim completion earned cash]
           ,[April total training and assessment earned]      
           ,[April learning support earned cash]
		   ,[April English and maths on programme earned cash]
           ,[April English and maths balancing payment earned cash]
		   ,[April disadvantage earned cash]
		   ,[April 16-18 additional payments for employers]
		   ,[April 16-18 additional payments for providers]
		   ,[April 16-18 framework uplift on programme payment]
		   ,[April 16-18 framework uplift balancing payment] 
		   ,[April 16-18 framework uplift completion payment]
           ,[May on programme earned cash]
           ,[May balancing payment earned cash]
           ,[May aim completion earned cash]
           ,[May total training and assessment earned]      
           ,[May learning support earned cash]
		   ,[May English and maths on programme earned cash]
           ,[May English and maths balancing payment earned cash]
		   ,[May disadvantage earned cash]
		   ,[May 16-18 additional payments for employers]
		   ,[May 16-18 additional payments for providers]
		   ,[May 16-18 framework uplift on programme payment]
		   ,[May 16-18 framework uplift balancing payment] 
		   ,[May 16-18 framework uplift completion payment]
           ,[June on programme earned cash]
           ,[June balancing payment earned cash]
           ,[June aim completion earned cash]
           ,[June total training and assessment earned]      
           ,[June learning support earned cash]
		   ,[June English and maths on programme earned cash]
           ,[June English and maths balancing payment earned cash]
		   ,[June disadvantage earned cash]
		   ,[June 16-18 additional payments for employers]
		   ,[June 16-18 additional payments for providers]
		   ,[June 16-18 framework uplift on programme payment]
		   ,[June 16-18 framework uplift balancing payment] 
		   ,[June 16-18 framework uplift completion payment]
           ,[July on programme earned cash]
           ,[July balancing payment earned cash]
           ,[July aim completion earned cash]
           ,[July total training and assessment earned]      
           ,[July learning support earned cash]
		   ,[July English and maths on programme earned cash]
           ,[July English and maths balancing payment earned cash]
		   ,[July disadvantage earned cash]
		   ,[July 16-18 additional payments for employers]
		   ,[July 16-18 additional payments for providers]
		   ,[July 16-18 framework uplift on programme payment]
		   ,[July 16-18 framework uplift balancing payment] 
		   ,[July 16-18 framework uplift completion payment]
           ,[Total on programme earned cash]
           ,[Total balancing payment earned cash]
           ,[Total aim completion earned cash]
           ,[Total training and assessment earned]
           ,[Total learning support earned cash]
		   ,[Total English and maths on programme earned cash]
		   ,[Total English and maths balancing payment earned cash]
		   ,[Total disadvantage earned cash]
		   ,[Total 16-18 additional payments for employers]
           ,[Total 16-18 additional payments for providers]
		   ,[Total 16-18 framework uplift on programme payment] 
		   ,[Total 16-18 framework uplift balancing payment]
		   ,[Total 16-18 framework uplift completion payment]
           ,[OFFICIAL - SENSITIVE]
  FROM [Report].[AppsIndicativeEarningsReport]
  		WHERE RowNumber BETWEEN ((@Page - 1) * @PageSize) AND (@Page * @PageSize - 1)
		Order by rownumber		

END

GO