IF OBJECT_ID('[Report].[PFRMainOccupancyReport]') IS NOT NULL
BEGIN
    DROP TABLE [Report].[PFRMainOccupancyReport]
END

CREATE TABLE [Report].[PFRMainOccupancyReport](
	[RowNumber] [bigint] NULL,
	[Learner reference number] [varchar](12) NULL,
	[Unique learner number] [bigint] NULL,
	[Date of birth] [varchar](10) NULL,
	[Postcode prior to enrolment] [varchar](8) NULL,
	[Pre-merger UKPRN] [int] NULL,
	[Provider specified learner monitoring (A)] [varchar](20) NULL,
	[Provider specified learner monitoring (B)] [varchar](20) NULL,
	[Aim sequence number] [int] NULL,
	[Learning aim reference] [varchar](8) NULL,
	[Learning aim title] [varchar](254) NULL,
	[Software supplier aim identifier] [varchar](36) NULL,
	[Applicable funding rate from ESOL hours] [decimal](10, 5) NULL,
	[Applicable funding rate] [decimal](10, 5) NULL,
	[Applicable programme weighting] [varchar](1) NULL,
	[Aim value] [decimal](10, 5) NULL,
	[Notional NVQ level] [varchar](5) NULL,
	[Tier 2 sector subject area] [decimal](5, 2) NULL,
	[Programme type] [int] NULL,
	[Framework code] [int] NULL,
	[Apprenticeship pathway] [int] NULL,
	[Aim type] [int] NULL,
	[Framework component type code] [int] NULL,
	[Funding model] [int] NOT NULL,
	[Funding adjustment for prior learning] [int] NULL,
	[Other funding adjustment] [int] NULL,
	[Original learning start date] [date] NULL,
	[Learning start date] [date] NULL,
	[Learning planned end date] [date] NULL,
	[Completion status] [int] NULL,
	[Learning actual end date] [date] NULL,
	[Outcome] [int] NULL,
	[Achievement date] [date] NULL,
	[Additional delivery hours] [int] NULL,
	[Learning delivery funding and monitoring type - source of funding] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - full or co funding indicator] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - eligibility for enhanced apprenticeship funding] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - learning support funding (highest applicable)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - LSF date applies from (earliest)] [date] NULL,
	[Learning delivery funding and monitoring type - LSF date applies to (latest)] [date] NULL,
	[Learning delivery funding and monitoring type - learning delivery monitoring (A)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - learning delivery monitoring (B)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - learning delivery monitoring (C)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - learning delivery monitoring (D)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - restart indicator] [varchar](5) NULL,
	[Provider specified delivery monitoring (A)] [varchar](20) NULL,
	[Provider specified delivery monitoring (B)] [varchar](20) NULL,
	[Provider specified delivery monitoring (C)] [varchar](20) NULL,
	[Provider specified delivery monitoring (D)] [varchar](20) NULL,
	[Funding line type] [varchar](100) NULL,
	[Planned number of on programme instalments] [int] NULL,
	[Transitional planned number of programme instalments from 1 August 2013] [int] NULL,
	[Transitional start proportion] [decimal](10, 5) NULL,
	[Achievement element (potential or actual earned cash)] [decimal](10, 5) NULL,
	[Achievement percentage (aggregated maximum value)] [decimal](15, 5) NULL,
	[Non-Govt contribution] [decimal](10, 5) NULL,
	[Sub contracted or partnership UKPRN] [int] NULL,
	[Delivery location postcode] [varchar](8) NULL,
	[Area uplift] [decimal](10, 5) NULL,
	[Disadvantage uplift] [decimal](10, 4) NULL,
	[Employer identifier] [int] NULL,
	[Large employer factor] [decimal](10, 2) NULL,
	[Capping factor] [decimal](10, 5) NULL,
	[Traineeship work placement or work preparation] [varchar](3) NULL,
	[Higher apprenticeship prescribed HE aim] [varchar](3) NULL,
	[Date used for employment factor lookups] [date] NULL,
	[Date used for other factor lookups] [date] NULL,
	[August on programme earned cash] [decimal](15, 5) NULL,
	[August balancing payment earned cash] [decimal](15, 5) NULL,
	[August aim achievement earned cash] [decimal](15, 5) NULL,
	[August job outcome earned cash] [decimal](15, 5) NULL,
	[August learning support earned cash] [decimal](15, 5) NULL,
	[September on programme earned cash] [decimal](15, 5) NULL,
	[September balancing payment earned cash] [decimal](15, 5) NULL,
	[September aim achievement earned cash] [decimal](15, 5) NULL,
	[September job outcome earned cash] [decimal](15, 5) NULL,
	[September learning support earned cash] [decimal](15, 5) NULL,
	[October on programme earned cash] [decimal](15, 5) NULL,
	[October balancing payment earned cash] [decimal](15, 5) NULL,
	[October aim achievement earned cash] [decimal](15, 5) NULL,
	[October job outcome earned cash] [decimal](15, 5) NULL,
	[October learning support earned cash] [decimal](15, 5) NULL,
	[November on programme earned cash] [decimal](15, 5) NULL,
	[November balancing payment earned cash] [decimal](15, 5) NULL,
	[November aim achievement earned cash] [decimal](15, 5) NULL,
	[November job outcome earned cash] [decimal](15, 5) NULL,
	[November learning support earned cash] [decimal](15, 5) NULL,
	[December on programme earned cash] [decimal](15, 5) NULL,
	[December balancing payment earned cash] [decimal](15, 5) NULL,
	[December aim achievement earned cash] [decimal](15, 5) NULL,
	[December job outcome earned cash] [decimal](15, 5) NULL,
	[December learning support earned cash] [decimal](15, 5) NULL,
	[January on programme earned cash] [decimal](15, 5) NULL,
	[January balancing payment earned cash] [decimal](15, 5) NULL,
	[January aim achievement earned cash] [decimal](15, 5) NULL,
	[January job outcome earned cash] [decimal](15, 5) NULL,
	[January learning support earned cash] [decimal](15, 5) NULL,
	[February on programme earned cash] [decimal](15, 5) NULL,
	[February balancing payment earned cash] [decimal](15, 5) NULL,
	[February aim achievement earned cash] [decimal](15, 5) NULL,
	[February job outcome earned cash] [decimal](15, 5) NULL,
	[February learning support earned cash] [decimal](15, 5) NULL,
	[March on programme earned cash] [decimal](15, 5) NULL,
	[March balancing payment earned cash] [decimal](15, 5) NULL,
	[March aim achievement earned cash] [decimal](15, 5) NULL,
	[March job outcome earned cash] [decimal](15, 5) NULL,
	[March learning support earned cash] [decimal](15, 5) NULL,
	[April on programme earned cash] [decimal](15, 5) NULL,
	[April balancing payment earned cash] [decimal](15, 5) NULL,
	[April aim achievement earned cash] [decimal](15, 5) NULL,
	[April job outcome earned cash] [decimal](15, 5) NULL,
	[April learning support earned cash] [decimal](15, 5) NULL,
	[May on programme earned cash] [decimal](15, 5) NULL,
	[May balancing payment earned cash] [decimal](15, 5) NULL,
	[May aim achievement earned cash] [decimal](15, 5) NULL,
	[May job outcome earned cash] [decimal](15, 5) NULL,
	[May learning support earned cash] [decimal](15, 5) NULL,
	[June on programme earned cash] [decimal](15, 5) NULL,
	[June balancing payment earned cash] [decimal](15, 5) NULL,
	[June aim achievement earned cash] [decimal](15, 5) NULL,
	[June job outcome earned cash] [decimal](15, 5) NULL,
	[June learning support earned cash] [decimal](15, 5) NULL,
	[July on programme earned cash] [decimal](15, 5) NULL,
	[July balancing payment earned cash] [decimal](15, 5) NULL,
	[July aim achievement earned cash] [decimal](15, 5) NULL,
	[July job outcome earned cash] [decimal](15, 5) NULL,
	[July learning support earned cash] [decimal](15, 5) NULL,
	[Total on programme earned cash] [decimal](26, 5) NULL,
	[Total balancing payment earned cash] [decimal](26, 5) NULL,
	[Total aim achievement earned cash] [decimal](26, 5) NULL,
	[Total job outcome earned cash] [decimal](26, 5) NULL,
	[Total learning support earned cash] [decimal](26, 5) NULL,
	[Total earned cash] [decimal](30, 5) NULL
)
GO

