IF OBJECT_ID('Report.PFRMainOccupancyReportView') IS NOT NULL
BEGIN
	DROP VIEW Report.PFRMainOccupancyReportView
END
GO


CREATE VIEW [Report].[PFRMainOccupancyReportView] 
AS

WITH MAXAchieveVal_CTE AS
( 
SELECT 
	LearnRefnumber
	,AimSeqNumber
	,Max(Achieve_Val) as Achieve_Val
FROM
(
SELECT [LearnRefNumber]
      ,[AimSeqNumber]
	  ,attributeName
       ,[Period_1]
      ,[Period_2]
      ,[Period_3]
      ,[Period_4]
      ,[Period_5]
      ,[Period_6]
      ,[Period_7]
      ,[Period_8]
      ,[Period_9]
      ,[Period_10]
      ,[Period_11]
      ,[Period_12]
  FROM [Rulebase].[SFA_LearningDelivery_PeriodisedValues]
  where attributeName='AchievePayPct'
  )PVT
  UNPIVOT (Achieve_Val for Period_ID in ([Period_1],[Period_2],[Period_3],[Period_4],[Period_5],[Period_6],[Period_7],[Period_8],[Period_9],[Period_10],[Period_11],[Period_12]))
 AS UNPVT 
 Group by LearnRefnumber
		,AimSeqNumber 
)
,OnProgPaymentValues_CTE AS 
(
SELECT *, [SumOfAllPeriods] =	ISNULL(Period_1,0) + ISNULL(Period_2,0) + ISNULL(Period_3,0) + ISNULL(Period_4,0) + ISNULL(Period_5,0) + ISNULL(Period_6,0)	+ ISNULL(Period_7,0) + ISNULL(Period_8,0) + ISNULL(Period_9,0) + ISNULL(Period_10,0) + ISNULL(Period_11,0) + ISNULL(Period_12,0)
FROM [Rulebase].[SFA_LearningDelivery_PeriodisedValues]  WHERE AttributeName ='OnProgPayment'
)
,BalancePaymentValues_CTE AS 
(
SELECT *, [SumOfAllPeriods] =	ISNULL(Period_1,0) + ISNULL(Period_2,0) + ISNULL(Period_3,0) + ISNULL(Period_4,0) + ISNULL(Period_5,0) + ISNULL(Period_6,0)	+ ISNULL(Period_7,0) + ISNULL(Period_8,0) + ISNULL(Period_9,0) + ISNULL(Period_10,0) + ISNULL(Period_11,0) + ISNULL(Period_12,0)
FROM [Rulebase].[SFA_LearningDelivery_PeriodisedValues] WHERE AttributeName ='BalancePayment'
)
,AchievePaymentValues_CTE AS 
(
SELECT *, [SumOfAllPeriods] =	ISNULL(Period_1,0) + ISNULL(Period_2,0) + ISNULL(Period_3,0) + ISNULL(Period_4,0) + ISNULL(Period_5,0) + ISNULL(Period_6,0)	+ ISNULL(Period_7,0) + ISNULL(Period_8,0) + ISNULL(Period_9,0) + ISNULL(Period_10,0) + ISNULL(Period_11,0) + ISNULL(Period_12,0)
FROM [Rulebase].[SFA_LearningDelivery_PeriodisedValues] WHERE AttributeName ='AchievePayment'
)
,EmpOutcomePayValues_CTE AS 
(
SELECT *, [SumOfAllPeriods] =	ISNULL(Period_1,0) + ISNULL(Period_2,0) + ISNULL(Period_3,0) + ISNULL(Period_4,0) + ISNULL(Period_5,0) + ISNULL(Period_6,0)	+ ISNULL(Period_7,0) + ISNULL(Period_8,0) + ISNULL(Period_9,0) + ISNULL(Period_10,0) + ISNULL(Period_11,0) + ISNULL(Period_12,0)
FROM [Rulebase].[SFA_LearningDelivery_PeriodisedValues] WHERE AttributeName ='EmpOutcomePay'
)
,LearnSuppFundCashValues_CTE AS 
(
SELECT *, [SumOfAllPeriods] =	ISNULL(Period_1,0) + ISNULL(Period_2,0) + ISNULL(Period_3,0) + ISNULL(Period_4,0) + ISNULL(Period_5,0) + ISNULL(Period_6,0)	+ ISNULL(Period_7,0) + ISNULL(Period_8,0) + ISNULL(Period_9,0) + ISNULL(Period_10,0) + ISNULL(Period_11,0) + ISNULL(Period_12,0)
FROM [Rulebase].[SFA_LearningDelivery_PeriodisedValues] WHERE AttributeName ='LearnSuppFundCash'
)
,ProvSpecLearnMon_CTE AS 
(
SELECT ProvSpecLearnMon.* FROM [Valid].[ProviderSpecLearnerMonitoring] PIVOT (MAX(ProvSpecLearnMon) FOR ProvSpecLearnMonOccur IN ([A],[B]))AS ProvSpecLearnMon
)
,ProvSpecDelMon_CTE AS 
(
SELECT ProvSpecDelMon.* FROM [Valid].[ProviderSpecDeliveryMonitoring] PIVOT (MAX(ProvSpecDelMon) FOR ProvSpecDelMonOccur IN ([A],[B],[C],[D]))AS ProvSpecDelMon
)
,LearnDelFAM_CTE_rn AS
(
select [LearnRefNumber],	[AimSeqNumber],	[LearnDelFAMType],	[LearnDelFAMCode]	
,CAST((ROW_NUMBER() OVER(PARTITION BY [LearnRefNumber],[AimSeqNumber] ORDER BY [LearnDelFAMCode] ))AS VARCHAR) AS RN
FROM  [Valid].[LearningDeliveryFAM]
WHERE [LearnDelFAMType] = 'LDM'
UNION
select [LearnRefNumber],	[AimSeqNumber],	[LearnDelFAMType],	[LearnDelFAMCode],'' AS RN
FROM  [Valid].[LearningDeliveryFAM]
WHERE [LearnDelFAMType] <> 'LDM'
)
,LearnDelFAM_CTE_pivdata AS
(
SELECT [LearnRefNumber],	[AimSeqNumber],	[LearnDelFAMType]+RN AS [LearnDelFAMType], [LearnDelFAMCode] FROM LearnDelFAM_CTE_rn
)
,LearnDelFAM_CTE AS
(
	SELECT * FROM  LearnDelFAM_CTE_pivdata f PIVOT( MAX(LearnDelFAMCode) FOR [LearnDelFAMType] IN ([ACT],[SOF],[FFI],[EEF],[LDM1],[LDM2],[LDM3],[LDM4],[RES])) LearnDelFAM 
)
,LearnDelFAM_LSF_CTE AS
(
	SELECT LearnRefNumber, AimSeqNumber, MAX(LearnDelFAMCode) LearnDelFAMCode, MIN(LearnDelFAMDateFrom) AS LearnDelFAMDateFrom_Earliest, MAX(LearnDelFAMDateTo) AS LearnDelFAMDateTo_Latest FROM  [Valid].[LearningDeliveryFAM] WHERE LearnDelFAMType ='LSF' GROUP BY LearnRefNumber,AimSeqNumber
)

,FM35_LearningDeliveries_CTE AS
(
SELECT DISTINCT
	[L].[LearnRefNumber]									AS [Learner reference number]
    ,[L].[ULN]												AS [Unique learner number]
	,CONVERT(VARCHAR(10), [L].[DateOfBirth]	, 103)			AS [Date of birth]							
	,[L].[PostcodePrior]									AS [Postcode prior to enrolment]
	,[L].[PMUKPRN]											AS [Pre-merger UKPRN]
	,[ProvSpecLearnMon].[A]									AS [Provider specified learner monitoring (A)]
	,[ProvSpecLearnMon].[B]									AS [Provider specified learner monitoring (B)]
    ,[LD].[AimSeqNumber]									AS [Aim sequence number] 
	,[LD].[LearnAimRef]										AS [Learning aim reference] 
	,[LD_SFA_INPUT].[LearnAimRefTitle]						AS [Learning aim title]
	,[LD].[SWSupAimID]										AS [Software supplier aim identifier]
	,[LD_SFA_FUND].[WeightedRateFromESOL]					AS [Applicable funding rate from ESOL hours]
	,[LD_SFA_FUND].[ApplicWeightFundRate]					AS [Applicable funding rate]
	,[LD_SFA_FUND].[ApplicProgWeightFact]					AS [Applicable programme weighting]
	,[LD_SFA_FUND].[AimValue]								AS [Aim value]
	,[LD_SFA_INPUT].[NotionalNVQLevelv2]					AS [Notional NVQ level] 
	,[LD_SFA_INPUT].[SectorSubjectAreaTier2]				AS [Tier 2 sector subject area] 
	,[LD].[ProgType]										AS [Programme type] 
	,[LD].[FworkCode]										AS [Framework code] 
	,[LD].[PwayCode]										AS [Apprenticeship pathway]
	,[LD].[AimType]											AS [Aim type] 
	,[LARS_FA].[FrameworkComponentType]						AS [Framework component type code]
	,[LD].[FundModel]										AS [Funding model]
	,[LD].[PriorLearnFundAdj]								AS [Funding adjustment for prior learning] 
	,[LD].[OtherFundAdj]									AS [Other funding adjustment] 
    ,[LD].[OrigLearnStartDate]								AS [Original learning start date] 
    ,[LD].[LearnStartDate]									AS [Learning start date] 
    ,[LD].[LearnPlanEndDate]								AS [Learning planned end date] 
    ,[LD].[CompStatus]										AS [Completion status] 
    ,[LD].[LearnActEndDate]									AS [Learning actual end date] 
    ,[LD].[Outcome]											AS [Outcome] 
    ,[LD].[AchDate]											AS [Achievement date]
	,[LD].[AddHours]										AS [Additional delivery hours]
    ,[LDFAM].[SOF]											AS [Learning delivery funding and monitoring type - source of funding]
    ,[LDFAM].[FFI]											AS [Learning delivery funding and monitoring type - full or co funding indicator]
    ,[LDFAM].[EEF]											AS [Learning delivery funding and monitoring type - eligibility for enhanced apprenticeship funding]
	,[LDFAM_LSF].[LearnDelFAMCode]							AS [Learning delivery funding and monitoring type - learning support funding (highest applicable)]
	,[LDFAM_LSF].[LearnDelFAMDateFrom_Earliest]				AS [Learning delivery funding and monitoring type - LSF date applies from (earliest)]
	,[LDFAM_LSF].[LearnDelFAMDateTo_Latest]				AS [Learning delivery funding and monitoring type - LSF date applies to (latest)]
	,[LDFAM].[LDM1]											AS [Learning delivery funding and monitoring type - learning delivery monitoring (A)]
	,[LDFAM].[LDM2]											AS [Learning delivery funding and monitoring type - learning delivery monitoring (B)]
	,[LDFAM].[LDM3]											AS [Learning delivery funding and monitoring type - learning delivery monitoring (C)]
	,[LDFAM].[LDM4]											AS [Learning delivery funding and monitoring type - learning delivery monitoring (D)]
	,[LDFAM].[RES]											AS [Learning delivery funding and monitoring type - restart indicator]
	,[ProvSpecDelMon].[A]									AS [Provider specified delivery monitoring (A)]
	,[ProvSpecDelMon].[B]									AS [Provider specified delivery monitoring (B)]
	,[ProvSpecDelMon].[C]									AS [Provider specified delivery monitoring (C)]
	,[ProvSpecDelMon].[D]									AS [Provider specified delivery monitoring (D)]
    ,[LD_SFA_FUND].[FundLine]								AS [Funding line type]
    ,[LD_SFA_FUND].[PlannedNumOnProgInstalm]				AS [Planned number of on programme instalments]
    ,[LD_SFA_FUND].[PlannedNumOnProgInstalmTrans]			AS [Transitional planned number of programme instalments from 1 August 2013]
    ,[LD_SFA_FUND].[StartPropTrans]							AS [Transitional start proportion]
	,[LD_SFA_FUND].[AchieveElement]							AS [Achievement element (potential or actual earned cash)]
	,[L_SFA_CTE].[Achieve_Val]								AS [Achievement percentage (aggregated maximum value)]
    ,[LD_SFA_FUND].[NonGovCont]								AS [Non-Govt contribution]
	,[LD].[PartnerUKPRN]									AS [Sub contracted or partnership UKPRN]
    ,[LD].[DelLocPostcode]									AS [Delivery location postcode]
	,[LD_SFA_FUND].[AreaCostFactAdj]						AS [Area uplift]
	,[LD_SFA_FUND].[DisUpFactAdj]						    AS [Disadvantage uplift]
    ,[LD_SFA_FUND].[LargeEmployerID]						AS [Employer identifier]
    ,[LD_SFA_FUND].[LargeEmployerSFAFctr]					AS [Large employer factor]
    ,[LD_SFA_FUND].[CapFactor]								AS [Capping factor]
	,CASE WHEN ([LD_SFA_FUND].[TrnWorkPlaceAim] = 'True' or [LD_SFA_FUND].[TrnWorkPrepAim] = 'True') THEN 'Yes' ELSE 'No' END AS [Traineeship work placement or work preparation]
	,CASE WHEN ([LD_SFA_FUND].[PrscHEAim] = 'True') THEN 'Yes' ELSE 'No' END AS [Higher apprenticeship prescribed HE aim]
	,[LD_SFA_FUND].[ApplicEmpFactDate]						AS [Date used for employment factor lookups]
    ,[LD_SFA_FUND].[ApplicFactDate]							AS [Date used for other factor lookups]

    ,ISNULL([OnProgPay].[Period_1], 0)						AS [August on programme earned cash]
    ,ISNULL([BalancePay].[Period_1], 0)						AS [August balancing payment earned cash]
    ,ISNULL([AchievePay].[Period_1], 0)						AS [August aim achievement earned cash]
    ,ISNULL([EmpOutcomePay].[Period_1], 0)					AS [August job outcome earned cash] 
    ,ISNULL([LrnSuppFundCash].[Period_1], 0)				AS [August learning support earned cash]	
    ,ISNULL([OnProgPay].[Period_2], 0)						AS [September on programme earned cash]
    ,ISNULL([BalancePay].[Period_2], 0)						AS [September balancing payment earned cash]
    ,ISNULL([AchievePay].[Period_2], 0)						AS [September aim achievement earned cash]
    ,ISNULL([EmpOutcomePay].[Period_2], 0)					AS [September job outcome earned cash]
    ,ISNULL([LrnSuppFundCash].[Period_2], 0)	AS [September learning support earned cash]
	,ISNULL([OnProgPay].[Period_3], 0)	AS [October on programme earned cash]
    ,ISNULL([BalancePay].[Period_3], 0)	AS [October balancing payment earned cash]
    ,ISNULL([AchievePay].[Period_3], 0)	AS [October aim achievement earned cash]
    ,ISNULL([EmpOutcomePay].[Period_3], 0)	AS [October job outcome earned cash]
    ,ISNULL([LrnSuppFundCash].[Period_3], 0)	AS [October learning support earned cash]
	,ISNULL([OnProgPay].[Period_4], 0)	AS [November on programme earned cash]
    ,ISNULL([BalancePay].[Period_4], 0)	AS [November balancing payment earned cash]
    ,ISNULL([AchievePay].[Period_4], 0)	AS [November aim achievement earned cash]
    ,ISNULL([EmpOutcomePay].[Period_4], 0)	AS [November job outcome earned cash]
    ,ISNULL([LrnSuppFundCash].[Period_4], 0)	AS [November learning support earned cash]
	,ISNULL([OnProgPay].[Period_5], 0)	AS [December on programme earned cash]
    ,ISNULL([BalancePay].[Period_5], 0)	AS [December balancing payment earned cash]
    ,ISNULL([AchievePay].[Period_5], 0)	AS [December aim achievement earned cash]
    ,ISNULL([EmpOutcomePay].[Period_5], 0)	AS [December job outcome earned cash]
    ,ISNULL([LrnSuppFundCash].[Period_5], 0)	AS [December learning support earned cash]
	,ISNULL([OnProgPay].[Period_6], 0)	AS [January on programme earned cash]
    ,ISNULL([BalancePay].[Period_6], 0)	AS [January balancing payment earned cash]
    ,ISNULL([AchievePay].[Period_6], 0)	AS [January aim achievement earned cash]
    ,ISNULL([EmpOutcomePay].[Period_6], 0)	AS [January job outcome earned cash]
    ,ISNULL([LrnSuppFundCash].[Period_6], 0)	AS [January learning support earned cash]
	,ISNULL([OnProgPay].[Period_7], 0)	AS [February on programme earned cash]
    ,ISNULL([BalancePay].[Period_7], 0)	AS [February balancing payment earned cash]
    ,ISNULL([AchievePay].[Period_7], 0)	AS [February aim achievement earned cash]
    ,ISNULL([EmpOutcomePay].[Period_7], 0)	AS [February job outcome earned cash]
    ,ISNULL([LrnSuppFundCash].[Period_7], 0)	AS [February learning support earned cash]
	,ISNULL([OnProgPay].[Period_8], 0)	AS [March on programme earned cash]
    ,ISNULL([BalancePay].[Period_8], 0)	AS [March balancing payment earned cash]
    ,ISNULL([AchievePay].[Period_8], 0)	AS [March aim achievement earned cash]
    ,ISNULL([EmpOutcomePay].[Period_8], 0)	AS [March job outcome earned cash]
    ,ISNULL([LrnSuppFundCash].[Period_8], 0)	AS [March learning support earned cash]
	,ISNULL([OnProgPay].[Period_9], 0)	AS [April on programme earned cash]
    ,ISNULL([BalancePay].[Period_9], 0)	AS [April balancing payment earned cash]
    ,ISNULL([AchievePay].[Period_9], 0)	AS [April aim achievement earned cash]
    ,ISNULL([EmpOutcomePay].[Period_9], 0)	AS [April job outcome earned cash]
    ,ISNULL([LrnSuppFundCash].[Period_9], 0)	AS [April learning support earned cash]
	,ISNULL([OnProgPay].[Period_10], 0)	AS [May on programme earned cash]
    ,ISNULL([BalancePay].[Period_10], 0)	AS [May balancing payment earned cash]
    ,ISNULL([AchievePay].[Period_10], 0)	AS [May aim achievement earned cash]
    ,ISNULL([EmpOutcomePay].[Period_10], 0)	AS [May job outcome earned cash]
    ,ISNULL([LrnSuppFundCash].[Period_10], 0)	AS [May learning support earned cash]
	,ISNULL([OnProgPay].[Period_11], 0)	AS [June on programme earned cash]
    ,ISNULL([BalancePay].[Period_11], 0)	AS [June balancing payment earned cash]
    ,ISNULL([AchievePay].[Period_11], 0)	AS [June aim achievement earned cash]
    ,ISNULL([EmpOutcomePay].[Period_11], 0)	AS [June job outcome earned cash]
    ,ISNULL([LrnSuppFundCash].[Period_11], 0)	AS [June learning support earned cash]
	,ISNULL([OnProgPay].[Period_12], 0)	AS [July on programme earned cash]
    ,ISNULL([BalancePay].[Period_12], 0)	AS [July balancing payment earned cash]
    ,ISNULL([AchievePay].[Period_12], 0)	AS [July aim achievement earned cash]
    ,ISNULL([EmpOutcomePay].[Period_12], 0)	AS [July job outcome earned cash]
    ,ISNULL([LrnSuppFundCash].[Period_12], 0)	AS [July learning support earned cash]
	,ISNULL([OnProgPay].[SumOfAllPeriods],0) AS [Total on programme earned cash]
	,ISNULL([BalancePay].[SumOfAllPeriods],0) AS [Total balancing payment earned cash]
	,ISNULL([AchievePay].[SumOfAllPeriods],0) AS [Total aim achievement earned cash]
	,ISNULL([EmpOutcomePay].[SumOfAllPeriods],0) AS [Total job outcome earned cash]
	,ISNULL([LrnSuppFundCash].[SumOfAllPeriods],0) AS [Total learning support earned cash]
	,ISNULL([OnProgPay].[SumOfAllPeriods],0) + ISNULL([BalancePay].[SumOfAllPeriods],0) + ISNULL([AchievePay].[SumOfAllPeriods],0) + ISNULL([EmpOutcomePay].[SumOfAllPeriods],0) + ISNULL([LrnSuppFundCash].[SumOfAllPeriods],0) AS [Total earned cash]
	
FROM [Valid].[LearningDelivery] [LD] 
LEFT JOIN [Reference].[LARS_LearningDelivery] [LD_SFA_INPUT] 
	ON	[LD_SFA_INPUT].[LearnAimRef] = [LD].[LearnAimRef]
LEFT JOIN [Reference].[LARS_FrameworkAims] [LARS_FA]
	--ON [LARS_FA].[LearnAimRef] = [LD].[LearnAimRef]
	ON [LARS_FA].[FworkCode]=[LD].[FworkCode]
	AND [LARS_FA].[ProgType]=[LD].[ProgType]
	AND [LARS_FA].[PwayCode]=[LD].[PwayCode]
	AND [LARS_FA].[LearnAimRef]=[LD].[LearnAimRef]
LEFT JOIN [Rulebase].[SFA_LearningDelivery] [LD_SFA_FUND] 
ON	[LD_SFA_FUND].[AimSeqNumber] = [LD].[AimSeqNumber] 
AND [LD_SFA_FUND].[LearnRefNumber] = [LD].[LearnRefNumber]
LEFT JOIN [LearnDelFAM_CTE] [LDFAM] ON	[LDFAM].[AimSeqNumber] = [LD].[AimSeqNumber] AND [LDFAM].[LearnRefNumber] = [LD].[LearnRefNumber]
LEFT JOIN [LearnDelFAM_LSF_CTE] [LDFAM_LSF] ON	[LDFAM_LSF].[AimSeqNumber] = [LD].[AimSeqNumber] AND [LDFAM_LSF].[LearnRefNumber] = [LD].[LearnRefNumber]
LEFT JOIN OnProgPaymentValues_CTE [OnProgPay] ON [OnProgPay].[LearnRefNumber] = [LD].[LearnRefNumber] AND [OnProgPay].[AimSeqNumber] = [LD].[AimSeqNumber]
LEFT JOIN BalancePaymentValues_CTE [BalancePay] ON [BalancePay].[LearnRefNumber] = [LD].[LearnRefNumber] AND [BalancePay].[AimSeqNumber] = [LD].[AimSeqNumber]
LEFT JOIN AchievePaymentValues_CTE [AchievePay] ON [AchievePay].[LearnRefNumber] = [LD].[LearnRefNumber] AND [AchievePay].[AimSeqNumber] = [LD].[AimSeqNumber]
LEFT JOIN EmpOutcomePayValues_CTE [EmpOutcomePay] ON [EmpOutcomePay].[LearnRefNumber] = [LD].[LearnRefNumber] AND [EmpOutcomePay].[AimSeqNumber] = [LD].[AimSeqNumber]
LEFT JOIN LearnSuppFundCashValues_CTE [LrnSuppFundCash] ON [LrnSuppFundCash].[LearnRefNumber] = [LD].[LearnRefNumber] AND [LrnSuppFundCash].[AimSeqNumber] = [LD].[AimSeqNumber]
LEFT JOIN ProvSpecLearnMon_CTE [ProvSpecLearnMon] ON [ProvSpecLearnMon].[LearnRefNumber] = [LD].[LearnRefNumber]
LEFT JOIN ProvSpecDelMon_CTE [ProvSpecDelMon] ON [ProvSpecDelMon].[LearnRefNumber] = [LD].[LearnRefNumber] AND [ProvSpecDelMon].[AimSeqNumber] = [LD].[AimSeqNumber]
LEFT JOIN [Valid].[Learner] AS [L] 
ON	[L].[LearnRefNumber] = [LD].[LearnRefNumber]    
LEFT JOIN MAXAchieveVal_CTE AS [L_SFA_CTE] 
ON	[L_SFA_CTE].[LearnRefNumber] = [LD].[LearnRefNumber]
AND [L_SFA_CTE].[AimSeqNumber] = [LD].[AimSeqNumber]
WHERE ([LD].[FundModel] = 35 ) 

GROUP BY
	[L].[LearnRefNumber]							
    ,[L].[ULN]										
    ,[L].[DateOfBirth]								
	,[L].[PostcodePrior]
	,[L].[PMUKPRN]								
	,[ProvSpecLearnMon].[A]						
	,[ProvSpecLearnMon].[B]						
    ,[LD].[AimSeqNumber]							 
	,[LD].[LearnAimRef]								
	,[LD_SFA_INPUT].[LearnAimRefTitle]				
	,[LD].[SWSupAimID]
	,[LD_SFA_FUND].[WeightedRateFromESOL]								
	,[LD_SFA_FUND].[ApplicWeightFundRate]			
	,[LD_SFA_FUND].[ApplicProgWeightFact]			
	,[LD_SFA_FUND].[AimValue]						
	,[LD_SFA_INPUT].[NotionalNVQLevelv2]			
	,[LD_SFA_INPUT].[SectorSubjectAreaTier2]	
	,[LD].[ProgType]								
	,[LD].[FworkCode]								
	,[LD].[PwayCode]								
	,[LD].[AimType]									
	,[LARS_FA].[FrameworkComponentType]	
	,[LD].[FundModel]								
	,[LD].[PriorLearnFundAdj]						
	,[LD].[OtherFundAdj]							
    ,[LD].[OrigLearnStartDate]						
    ,[LD].[LearnStartDate]							 
    ,[LD].[LearnPlanEndDate]						
    ,[LD].[CompStatus]								
    ,[LD].[LearnActEndDate]							
    ,[LD].[Outcome]									
    ,[LD].[AchDate]
	,[LD].[AddHours]								
    ,[LDFAM].[SOF]							
    ,[LDFAM].[FFI]							
    ,[LDFAM].[EEF]		  					
	,[LDFAM].[LDM1]							
	,[LDFAM].[LDM2]							
	,[LDFAM].[LDM3]							
	,[LDFAM].[LDM4]							
	,[LDFAM].[RES]	
	,[LDFAM_LSF].[LearnDelFAMCode]
	,[LDFAM_LSF].[LearnDelFAMDateFrom_Earliest]
	,[LDFAM_LSF].[LearnDelFAMDateTo_Latest]
	,[ProvSpecDelMon].[A]						
	,[ProvSpecDelMon].[B]						
	,[ProvSpecDelMon].[C]						
	,[ProvSpecDelMon].[D]						
    ,[LD_SFA_FUND].[FundLine]						
    ,[LD_SFA_FUND].[PlannedNumOnProgInstalm]		
    ,[LD_SFA_FUND].[PlannedNumOnProgInstalmTrans]	
    ,[LD_SFA_FUND].[StartPropTrans]					
    ,[LD_SFA_FUND].[AchieveElement]					
	,[L_SFA_CTE].[Achieve_Val]					
    ,[LD_SFA_FUND].[NonGovCont]						
	,[LD].[PartnerUKPRN]							
    ,[LD].[DelLocPostcode]							
	,[LD_SFA_FUND].[AreaCostFactAdj]
	,[LD_SFA_FUND].[DisUpFactAdj]				
    ,[LD_SFA_FUND].[LargeEmployerID]				
    ,[LD_SFA_FUND].[LargeEmployerSFAFctr]			
    ,[LD_SFA_FUND].[CapFactor]	
	,[LD_SFA_FUND].[ApplicEmpFactDate]	
	,[LD_SFA_FUND].[ApplicFactDate]	
	,[LD_SFA_FUND].[TrnWorkPlaceAim]
	,[LD_SFA_FUND].[PrscHEAim]
	,[LD_SFA_FUND].[TrnWorkPrepAim]	
	,[OnProgPay].[Period_1]
    ,[BalancePay].[Period_1]
    ,[AchievePay].[Period_1]
    ,[EmpOutcomePay].[Period_1]
    ,[LrnSuppFundCash].[Period_1]	
	,[OnProgPay].[Period_2]
    ,[BalancePay].[Period_2]
    ,[AchievePay].[Period_2]
    ,[EmpOutcomePay].[Period_2]
    ,[LrnSuppFundCash].[Period_2]		
	,[OnProgPay].[Period_3]
    ,[BalancePay].[Period_3]
    ,[AchievePay].[Period_3]
    ,[EmpOutcomePay].[Period_3]
    ,[LrnSuppFundCash].[Period_3]		
	,[OnProgPay].[Period_4]
    ,[BalancePay].[Period_4]
    ,[AchievePay].[Period_4]
    ,[EmpOutcomePay].[Period_4]
    ,[LrnSuppFundCash].[Period_4]		
	,[OnProgPay].[Period_5]
    ,[BalancePay].[Period_5]
    ,[AchievePay].[Period_5]
    ,[EmpOutcomePay].[Period_5]
    ,[LrnSuppFundCash].[Period_5]		
	,[OnProgPay].[Period_6]
    ,[BalancePay].[Period_6]
    ,[AchievePay].[Period_6]
    ,[EmpOutcomePay].[Period_6]
    ,[LrnSuppFundCash].[Period_6]		
	,[OnProgPay].[Period_7]
    ,[BalancePay].[Period_7]
    ,[AchievePay].[Period_7]
    ,[EmpOutcomePay].[Period_7]
    ,[LrnSuppFundCash].[Period_7]		
	,[OnProgPay].[Period_8]
    ,[BalancePay].[Period_8]
    ,[AchievePay].[Period_8]
    ,[EmpOutcomePay].[Period_8]
    ,[LrnSuppFundCash].[Period_8]		
	,[OnProgPay].[Period_9]
    ,[BalancePay].[Period_9]
    ,[AchievePay].[Period_9]
    ,[EmpOutcomePay].[Period_9]
	,[LrnSuppFundCash].[Period_9]		
	,[OnProgPay].[Period_10]
    ,[BalancePay].[Period_10]
    ,[AchievePay].[Period_10]
    ,[EmpOutcomePay].[Period_10]
    ,[LrnSuppFundCash].[Period_10]		
	,[OnProgPay].[Period_11]
    ,[BalancePay].[Period_11]
    ,[AchievePay].[Period_11]
    ,[EmpOutcomePay].[Period_11]
    ,[LrnSuppFundCash].[Period_11]		
	,[OnProgPay].[Period_12]
    ,[BalancePay].[Period_12]
    ,[AchievePay].[Period_12]
    ,[EmpOutcomePay].[Period_12]
    ,[LrnSuppFundCash].[Period_12]	
	,[BalancePay].[SumOfAllPeriods]
	,[OnProgPay].[SumOfAllPeriods]
	,[AchievePay].[SumOfAllPeriods]
	,[EmpOutcomePay].[SumOfAllPeriods]
	,[LrnSuppFundCash].[SumOfAllPeriods]
	
)
--SELECT * FROM FM35_LearningDeliveries_CTE 
,FM25_Learners_CTE AS
(
SELECT DISTINCT
	[L].[LearnRefNumber]										AS [Learner reference number] 
    ,[L].[ULN]													AS [Unique learner number] 
    ,CONVERT(VARCHAR(10), [L].[DateOfBirth]	, 103)				AS [Date of birth]				
    ,[L].[PostcodePrior]										AS [Postcode prior to enrolment]
	,[L].[PMUKPRN]												AS [Pre-merger UKPRN]
	,[ProvSpecLearnMon].[A]										AS [Provider specified learner monitoring (A)]
	,[ProvSpecLearnMon].[B]										AS [Provider specified learner monitoring (B)]
	,NULL														AS [Aim sequence number] 
    ,NUll														AS [Learning aim reference] 
    ,NULL														AS [Learning aim title] 
	,NULL														AS [Software supplier aim identifier]
	,NULL														AS [Applicable funding rate from ESOL hours]
    ,FM25_L.[NatRate]											AS [Applicable funding rate]										 
    ,NUll														AS [Applicable programme weighting]
	,NULL														AS [Aim value] 
    ,NULL														AS [Notional NVQ level] 
    ,NULL														AS [Tier 2 sector subject area] 
    ,NUll														AS [Programme type] 
    ,NULL														AS [Framework code] 
    ,NULL														AS [Apprenticeship pathway] 
    ,NULL														AS [Aim type] 
    ,NULL														AS [Framework component type code] 
    ,[LD].FundModel												AS [Funding model] 
    ,NULL														AS [Funding adjustment for prior learning] 
    ,NULL														AS [Other funding adjustment] 
    ,NULL														AS [Original learning Start Date] 
	,[FM25_L].[LearnerStartDate]								AS [Learning start date] 
    ,[FM25_L].[LearnerPlanEndDate]								AS [Learning planned end date] 
    ,NULL														AS [Completion status] 
    ,[FM25_L].[LearnerActEndDate]								AS [Learning actual end date] 
    ,NULL														AS [Outcome] 
    ,NULL														AS [Achievement date]
	,NULL														AS [Additional delivery hours]
    ,NULL														AS [Learning delivery funding and monitoring type - source of funding] 
    ,NUll														AS [Learning delivery funding and monitoring type - full or co funding indicator] 
    ,NUll														AS [Learning delivery funding and monitoring type - eligibility for enhanced Apprenticeship funding] 
    ,NUll														AS [Learning delivery funding and monitoring type - learning support funding (highest applicable)] 
    ,NUll														AS [Learning delivery funding and monitoring type - LSF date applies from (earliest)] 
	,NUll														AS [Learning delivery funding and monitoring type - LSF date applies to (latest)] 
    ,NUll														AS [Learning delivery funding and monitoring type - learning delivery monitoring (A)] 
    ,NUll														AS [Learning delivery funding and monitoring type - learning delivery monitoring (B)] 
    ,NUll														AS [Learning delivery funding and monitoring type - learning delivery monitoring (C)] 
    ,NUll														AS [Learning delivery funding and monitoring type - learning delivery monitoring (D)] 
	,NUll														AS [Learning delivery funding and monitoring type - restart indicator]
    ,NUll														AS [Provider specified delivery monitoring (A)] 
    ,NUll														AS [Provider specified delivery monitoring (B)] 
    ,NUll														AS [Provider specified delivery monitoring (C)] 
    ,NUll														AS [Provider specified delivery monitoring (D)]
    ,[FM25_L].[FundLine]										AS [Funding line type]
    ,NULL														AS [Planned number of on programme instalments]
    ,NULL														AS [Transitional planned number of programme instalments from 1 August 2013] 
    ,NULL														AS [Transitional start proportion] 
	,NULL														AS [Achievement element (potential or actual earned cash)]
    ,NULL														AS [Achievement percentage (aggregated maximum value)]
    ,NULL														AS [Non-Govt contribution]
    ,NULL														AS [Sub contracted or partnership UKPRN] 
    ,NULL														AS [Delivery location postcode] 
    ,NULL														AS [Area uplift] 
	,NULL														AS [Disadvantage uplift] 
    ,NULL														AS [Employer identifier] 
    ,NULL														AS [Large employer factor]
    ,NULL														AS [Capping factor]
	,NULL														AS [Traineeship work placement or work preparation]
	,NULL														AS [Higher apprenticeship prescribed HE aim]
	,NULL														AS [Date used for employment factor lookups]
    ,NULL														AS [Date used for other factor lookups]
	,[L_SFA_EFA_FUND_PERIOD].[Period_1]							AS [August on programme earned cash]
	,NULL														AS [August balancing payment earned cash] 
    ,NULL														AS [August aim achievement earned cash] 
    ,NULL														AS [August job outcome earned cash]
    ,NULL														AS [August learning support earned cash] 	
	,[L_SFA_EFA_FUND_PERIOD].[Period_2]							AS [September on programme earned cash]
	,NULL														AS [September balancing payment earned cash] 
    ,NULL														AS [September aim achievement earned cash] 
    ,NULL														AS [September job outcome earned cash]
    ,NULL														AS [September learning support earned cash] 
	,[L_SFA_EFA_FUND_PERIOD].[Period_3]							AS [October on programme earned cash]
	,NULL														AS [October balancing payment earned cash] 
    ,NULL														AS [October aim achievement earned cash] 
    ,NULL														AS [October job outcome earned cash]
    ,NULL														AS [October learning support earned cash] 	
	,[L_SFA_EFA_FUND_PERIOD].[Period_4]							AS [November on programme earned cash]
	,NULL														AS [November balancing payment earned cash] 
    ,NULL														AS [November aim achievement earned cash] 
    ,NULL														AS [November job outcome earned cash]
    ,NULL														AS [November learning support earned cash] 		
	,[L_SFA_EFA_FUND_PERIOD].[Period_5]							AS [December on programme earned cash]
	,NULL														AS [December balancing payment earned cash] 
    ,NULL														AS [December aim achievement earned cash] 
    ,NULL														AS [December job outcome earned cash]
    ,NULL														AS [December learning support earned cash] 	
	,[L_SFA_EFA_FUND_PERIOD].[Period_6]							AS [January on programme earned cash]
	,NULL														AS [January balancing payment earned cash] 
    ,NULL														AS [January aim achievement earned cash] 
    ,NULL														AS [January job outcome earned cash]
    ,NULL														AS [January learning support earned cash] 		
	,[L_SFA_EFA_FUND_PERIOD].[Period_7]							AS [February on programme earned cash]
	,NULL														AS [February balancing payment earned cash] 
    ,NULL														AS [February aim achievement earned cash] 
    ,NULL														AS [February job outcome earned cash]
    ,NULL														AS [February learning support earned cash] 	
	,[L_SFA_EFA_FUND_PERIOD].[Period_8]							AS [March on programme earned cash]
	,NULL														AS [March balancing payment earned cash] 
    ,NULL														AS [March aim achievement earned cash] 
    ,NULL														AS [March job outcome earned cash]
    ,NULL														AS [March learning support earned cash] 	
	,[L_SFA_EFA_FUND_PERIOD].[Period_9]							AS [April on programme earned cash]
	,NULL														AS [April balancing payment earned cash] 
    ,NULL														AS [April aim achievement earned cash] 
    ,NULL														AS [April job outcome earned cash]
    ,NULL														AS [April learning support earned cash] 		
	,[L_SFA_EFA_FUND_PERIOD].[Period_10]						AS [May on programme earned cash]
	,NULL														AS [May balancing payment earned cash] 
    ,NULL														AS [May aim achievement earned cash] 
    ,NULL														AS [May job outcome earned cash]
    ,NULL														AS [May learning support earned cash] 	
	,[L_SFA_EFA_FUND_PERIOD].[Period_11]						AS [June on programme earned cash]
	,Null														AS [June balancing payment earned cash] 
    ,NULL														AS [June aim achievement earned cash] 
    ,NULL														AS [June job outcome earned cash]
    ,NULL														AS [June learning support earned cash] 	
	,[L_SFA_EFA_FUND_PERIOD].[Period_12]						AS [July on programme earned cash]
	,NULL														AS [July balancing payment earned cash] 
    ,NULL														AS [July aim achievement earned cash] 
    ,NULL														AS [July job outcome earned cash]
    ,NULL														AS [July learning support earned cash]
	,ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_1], 0)	+ ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_2], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_3], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_4], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_5], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_6], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_7], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_8], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_9], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_10], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_11], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_12], 0) AS [Total on programme earned cash]
	,NULL														AS [Total balancing payment earned cash]
	,NULL														AS [Total aim achievement earned cash]
	,NULL														AS [Total job outcome earned cash]
	,NULL														AS [Total learning support earned cash]
	,ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_1], 0)	+ ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_2], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_3], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_4], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_5], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_6], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_7], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_8], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_9], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_10], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_11], 0) + ISNULL([L_SFA_EFA_FUND_PERIOD].[Period_12], 0) AS [Total earned cash]
FROM [Valid].[LearningDelivery] [LD] 
LEFT JOIN [Valid].[Learner] AS [L] ON [L].[LearnRefNumber] = [LD].[LearnRefNumber]  
LEFT JOIN [Rulebase].[FM25_Learner] AS [FM25_L] ON FM25_L.LearnRefNumber = LD.LearnRefNumber  
LEFT JOIN [Rulebase].[EFA_SFA_Learner_PeriodisedValues] [L_SFA_EFA_FUND_PERIOD] ON [LD].[LearnRefNumber] = [L_SFA_EFA_FUND_PERIOD].[LearnRefNumber]
AND [L_SFA_EFA_FUND_PERIOD].AttributeName ='LnrOnProgPay' 
LEFT JOIN ProvSpecLearnMon_CTE [ProvSpecLearnMon] ON [ProvSpecLearnMon].[LearnRefNumber] = [LD].[LearnRefNumber]
INNER JOIN [LearnDelFAM_CTE] [LDFAM] ON	[LDFAM].[AimSeqNumber] = [LD].[AimSeqNumber] AND [LDFAM].[LearnRefNumber] = [LD].[LearnRefNumber]
WHERE [LD].[FundModel] = 25 AND [LDFAM].[SOF] = 105
)

--SELECT * FROM FM25_Learners_CTE
SELECT 
Row_Number() OVER (ORDER BY q1.[Learner reference number], q1.[Aim sequence number]  ASC) as RowNumber
,q1.* FROM
(
SELECT * FROM FM35_LearningDeliveries_CTE 
UNION SELECT * FROM FM25_Learners_CTE
) q1
