IF OBJECT_ID('[Report].[ALLBOccupancyReportData]') IS NOT NULL
BEGIN
    DROP TABLE [Report].[ALLBOccupancyReportData]
END
GO

CREATE TABLE [Report].[ALLBOccupancyReportData] (
    [Learner_reference_number] VARCHAR(12) NULL,
    [Unique_learner_number] BIGINT NULL,
    [Date_of_birth] VARCHAR(10) NULL,
    [PMUKPRN] int NULL,
    [Provider_specified_learner_monitoring_A] VARCHAR(20) NULL,
    [Provider_specified_learner_monitoring_B] VARCHAR(20) NULL,
    [Aim_sequence_number] INT NOT NULL,
    [Learning_aim_reference] VARCHAR(8) NOT NULL,
    [Learning_aim_title] VARCHAR(254) NULL,
    [Software_supplier_aim_identifier] VARCHAR(36) NULL,
    [Applicable_funding_rate] DECIMAL(10,4) NULL,
    [Applicable_programme_weighting] VARCHAR(1) NULL,
    [Notional_NVQ_level] VARCHAR(5) NULL,
    [Tier_2_sector_subject_area] DECIMAL(5,2) NULL,
    [Aim_type] INT NOT NULL,
    [Funding_model] INT NOT NULL,
    [Funding_adjustment_for_prior_learning] INT NULL,
    [Other_funding_adjustment] INT NULL,
    [Original_learning_start_date] DATE NULL,
    [Learning_start_date] DATE NOT NULL,
    [Learning_planned_end_date] DATE NOT NULL,
    [Completion_status] INT NULL,
    [Learning_actual_end_date] DATE NULL,
    [Outcome] INT NULL,
    [Learning_delivery_funding_and_monitoring_type_Advanced_Learner_Loans_indicator] VARCHAR(5) NULL,
    [Learning_delivery_funding_and_monitoring_type_Advanced_Learner_Loans_Bursary_funding] VARCHAR(5) NULL,
    [Learning_delivery_funding_and_monitoring_ALB_date_applies_from] DATE NULL,
    [Learning_delivery_funding_and_monitoring_ALB_date_applies_to] DATE NULL,
    [Learning_delivery_funding_and_monitoring_type_learning_delivery_monitoring_A] VARCHAR(5) NULL,
    [Learning_delivery_funding_and_monitoring_type_learning_delivery_monitoring_B] VARCHAR(5) NULL,
    [Learning_delivery_funding_and_monitoring_type_learning_delivery_monitoring_C] VARCHAR(5) NULL,
    [Learning_delivery_funding_and_monitoring_type_learning_delivery_monitoring_D] VARCHAR(5) NULL,
    [Provider_specified_delivery_monitoring_A] VARCHAR(20) NULL,
    [Provider_specified_delivery_monitoring_B] VARCHAR(20) NULL,
    [Provider_specified_delivery_monitoring_C] VARCHAR(20) NULL,
    [Provider_specified_delivery_monitoring_D] VARCHAR(20) NULL,
    [Sub_contracted_or_partnership_UKPRN] INT NULL,
    [Delivery_location_postcode] VARCHAR(8) NULL,
    [Area_uplift] DECIMAL(10,5) NULL,
    [Funding_line_type] VARCHAR(50) NULL,
    [First_liability_date] DATE NULL,
    [Planned_number_of_instalments] INT NULL,
    [Date_used_for_factor_lookups] DATE NULL,
    [August_ALB_code_used] DECIMAL(15,5) NULL,
    [August_ALB_support_payment_earned_cash] DECIMAL(15,5) NULL,
    [August_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(15,5) NULL,
    [August_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(15,5) NULL,
    [August_loans_bursary_total_earned_cash] DECIMAL(17,5) NULL,
    [September_ALB_Code_used] DECIMAL(15,5) NULL,
    [September_ALB_support_payment_earned_cash] DECIMAL(15,5) NULL,
    [September_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(15,5) NULL,
    [September_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(15,5) NULL,
    [September_loans_bursary_total_earned_cash] DECIMAL(17,5) NULL,
    [October_ALB_Code_used] DECIMAL(15,5) NULL,
    [October_ALB_support_payment_earned_cash] DECIMAL(15,5) NULL,
    [October_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(15,5) NULL,
    [October_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(15,5) NULL,
    [October_loans_bursary_total_earned_cash] DECIMAL(17,5) NULL,
    [November_ALB_Code_used] DECIMAL(15,5) NULL,
    [November_ALB_support_payment_earned_cash] DECIMAL(15,5) NULL,
    [November_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(15,5) NULL,
    [November_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(15,5) NULL,
    [November_loans_bursary_total_earned_cash] DECIMAL(17,5) NULL,
    [December_ALB_Code_used] DECIMAL(15,5) NULL,
    [December_ALB_support_payment_earned_cash] DECIMAL(15,5) NULL,
    [December_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(15,5) NULL,
    [December_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(15,5) NULL,
    [December_loans_bursary_total_earned_cash] DECIMAL(17,5) NULL,
    [January_ALB_Code_used] DECIMAL(15,5) NULL,
    [January_ALB_support_payment_earned_cash] DECIMAL(15,5) NULL,
    [January_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(15,5) NULL,
    [January_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(15,5) NULL,
    [January_loans_bursary_total_earned_cash] DECIMAL(17,5) NULL,
    [February_ALB_Code_used] DECIMAL(15,5) NULL,
    [February_ALB_support_payment_earned_cash] DECIMAL(15,5) NULL,
    [February_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(15,5) NULL,
    [February_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(15,5) NULL,
    [February_loans_bursary_total_earned_cash] DECIMAL(17,5) NULL,
    [March_ALB_Code_used] DECIMAL(15,5) NULL,
    [March_ALB_support_payment_earned_cash] DECIMAL(15,5) NULL,
    [March_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(15,5) NULL,
    [March_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(15,5) NULL,
    [March_loans_bursary_total_earned_cash] DECIMAL(17,5) NULL,
    [April_ALB_Code_used] DECIMAL(15,5) NULL,
    [April_ALB_support_payment_earned_cash] DECIMAL(15,5) NULL,
    [April_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(15,5) NULL,
    [April_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(15,5) NULL,
    [April_loans_bursary_total_earned_cash] DECIMAL(17,5) NULL,
    [May_ALB_Code_used] DECIMAL(15,5) NULL,
    [May_ALB_support_payment_earned_cash] DECIMAL(15,5) NULL,
    [May_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(15,5) NULL,
    [May_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(15,5) NULL,
    [May_loans_bursary_total_earned_cash] DECIMAL(17,5) NULL,
    [June_ALB_Code_used] DECIMAL(15,5) NULL,
    [June_ALB_support_payment_earned_cash] DECIMAL(15,5) NULL,
    [June_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(15,5) NULL,
    [June_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(15,5) NULL,
    [June_loans_bursary_total_earned_cash] DECIMAL(17,5) NULL,
    [July_ALB_Code_used] DECIMAL(15,5) NULL,
    [July_ALB_support_payment_earned_cash] DECIMAL(15,5) NULL,
    [July_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(15,5) NULL,
    [July_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(15,5) NULL,
    [July_loans_bursary_total_earned_cash] DECIMAL(17,5) NULL,
    [Total_ALB_support_payment_earned_cash] DECIMAL(26,5) NULL,
    [Total_loans_bursary_for_area_costs_on_programme_earned_cash] DECIMAL(26,5) NULL,
    [Total_loans_bursary_for_area_costs_balancing_earned_cash] DECIMAL(26,5) NULL,
    [Total_earned_cash] DECIMAL(38,5) NULL,
    [OFFICIAL_SENSITIVE]  VARCHAR(20) NOT NULL
)
GO
