IF EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[Report].[GetALLBOccupancyReportData]') AND type in (N'P', N'PC'))
	DROP PROCEDURE [Report].[GetALLBOccupancyReportData]
GO

CREATE PROCEDURE [Report].[GetALLBOccupancyReportData]
	@Page INT,
	@PageSize INT
AS
BEGIN
	SELECT 
		[Learner_reference_number] AS [Learner reference number], 
		[Unique_learner_number] AS [Unique learner number], 
		[Date_of_birth] AS [Date of birth], 
		[PMUKPRN] AS [Pre-merger UKPRN], 
		[Provider_specified_learner_monitoring_A] AS [Provider specified learner monitoring (A)], 
		[Provider_specified_learner_monitoring_B] AS [Provider specified learner monitoring (B)], 
		[Aim_sequence_number] AS [Aim sequence number], 
		[Learning_aim_reference] AS [Learning aim reference], 
		[Learning_aim_title] AS [Learning aim title], 
		[Software_supplier_aim_identifier] AS [Software supplier aim identifier], 
		[Applicable_funding_rate] AS [Applicable funding rate], 
		[Applicable_programme_weighting] AS [Applicable programme weighting], 
		[Notional_NVQ_level] AS [Notional NVQ level], 
		[Tier_2_sector_subject_area] AS [Tier 2 sector subject area], 
		[Aim_type] AS [Aim type], 
		[Funding_model] AS [Funding model], 
		[Funding_adjustment_for_prior_learning] AS [Funding adjustment for prior learning], 
		[Other_funding_adjustment] AS [Other funding adjustment], 
		CASE WHEN [Original_learning_start_date] IS NULL THEN '' ELSE  CONVERT(VARCHAR(10), [Original_learning_start_date],103) END AS [Original learning start date],
		CASE WHEN [Learning_start_date] IS NULL THEN '' ELSE  CONVERT(VARCHAR(10), [Learning_start_date],103) END AS [Learning start date],
		CASE WHEN [Learning_planned_end_date] IS NULL THEN '' ELSE  CONVERT(VARCHAR(10), [Learning_planned_end_date],103) END AS [Learning planned end date],		
		[Completion_status] AS [Completion status], 
		CASE WHEN [Learning_actual_end_date] IS NULL THEN '' ELSE  CONVERT(VARCHAR(10), [Learning_actual_end_date],103) END AS [Learning actual end date],
		[Outcome] AS [Outcome], 
		[Learning_delivery_funding_and_monitoring_type_Advanced_Learner_Loans_indicator] AS [Learning delivery funding and monitoring type - Advanced Learner Loans indicator], 
		[Learning_delivery_funding_and_monitoring_type_Advanced_Learner_Loans_Bursary_funding] AS [Learning delivery funding and monitoring type - Advanced Learner Loans Bursary funding], 
		CASE WHEN [Learning_delivery_funding_and_monitoring_ALB_date_applies_from] IS NULL THEN '' ELSE  CONVERT(VARCHAR(10), [Learning_delivery_funding_and_monitoring_ALB_date_applies_from],103) END AS [Learning delivery funding and monitoring - ALB date applies from],		
		CASE WHEN [Learning_delivery_funding_and_monitoring_ALB_date_applies_to] IS NULL THEN '' ELSE  CONVERT(VARCHAR(10), [Learning_delivery_funding_and_monitoring_ALB_date_applies_to],103) END AS [Learning delivery funding and monitoring - ALB date applies to],
		[Learning_delivery_funding_and_monitoring_type_learning_delivery_monitoring_A] AS [Learning delivery funding and monitoring type - learning delivery monitoring (A)], 
		[Learning_delivery_funding_and_monitoring_type_learning_delivery_monitoring_B] AS [Learning delivery funding and monitoring type - learning delivery monitoring (B)], 
		[Learning_delivery_funding_and_monitoring_type_learning_delivery_monitoring_C] AS [Learning delivery funding and monitoring type - learning delivery monitoring (C)], 
		[Learning_delivery_funding_and_monitoring_type_learning_delivery_monitoring_D] AS [Learning delivery funding and monitoring type - learning delivery monitoring (D)], 
		[Provider_specified_delivery_monitoring_A] AS [Provider specified delivery monitoring (A)], 
		[Provider_specified_delivery_monitoring_B] AS [Provider specified delivery monitoring (B)], 
		[Provider_specified_delivery_monitoring_C] AS [Provider specified delivery monitoring (C)], 
		[Provider_specified_delivery_monitoring_D] AS [Provider specified delivery monitoring (D)], 
		[Sub_contracted_or_partnership_UKPRN] AS [Sub contracted or partnership UKPRN], 
		[Delivery_location_postcode] AS [Delivery location postcode], 
		[Area_uplift] AS [Area uplift], 
		[Funding_line_type] AS [Funding line type], 
		CASE WHEN [First_liability_date] IS NULL THEN '' ELSE  CONVERT(VARCHAR(10), [First_liability_date],103) END AS [First liability date],		
		[Planned_number_of_instalments] AS [Planned number of instalments], 
		CASE WHEN [Date_used_for_factor_lookups] IS NULL THEN '' ELSE  CONVERT(VARCHAR(10), [Date_used_for_factor_lookups],103) END AS [Date used for factor lookups],		
		[August_ALB_code_used] AS [August ALB code used], 
		[August_ALB_support_payment_earned_cash] AS [August ALB support payment earned cash], 
		[August_loans_bursary_for_area_costs_on_programme_earned_cash] AS [August loans bursary for area costs on programme earned cash], 
		[August_loans_bursary_for_area_costs_balancing_earned_cash] AS [August loans bursary for area costs balancing earned cash], 
		[August_loans_bursary_total_earned_cash] AS [August loans bursary total earned cash], 
		[September_ALB_Code_used] AS [September ALB code used], 
		[September_ALB_support_payment_earned_cash] AS [September ALB support payment earned cash], 
		[September_loans_bursary_for_area_costs_on_programme_earned_cash] AS [September loans bursary for area costs on programme earned cash], 
		[September_loans_bursary_for_area_costs_balancing_earned_cash] AS [September loans bursary for area costs balancing earned cash], 
		[September_loans_bursary_total_earned_cash] AS [September loans bursary total earned cash], 
		[October_ALB_Code_used] AS [October ALB code used], 
		[October_ALB_support_payment_earned_cash] AS [October ALB support payment earned cash], 
		[October_loans_bursary_for_area_costs_on_programme_earned_cash] AS [October loans bursary for area costs on programme earned cash], 
		[October_loans_bursary_for_area_costs_balancing_earned_cash] AS [October loans bursary for area costs balancing earned cash], 
		[October_loans_bursary_total_earned_cash] AS [October loans bursary total earned cash], 
		[November_ALB_Code_used] AS [November ALB code used], 
		[November_ALB_support_payment_earned_cash] AS [November ALB support payment earned cash], 
		[November_loans_bursary_for_area_costs_on_programme_earned_cash] AS [November loans bursary for area costs on programme earned cash], 
		[November_loans_bursary_for_area_costs_balancing_earned_cash] AS [November loans bursary for area costs balancing earned cash], 
		[November_loans_bursary_total_earned_cash] AS [November loans bursary total earned cash], 
		[December_ALB_Code_used] AS [December ALB code used], 
		[December_ALB_support_payment_earned_cash] AS [December ALB support payment earned cash], 
		[December_loans_bursary_for_area_costs_on_programme_earned_cash] AS [December loans bursary for area costs on programme earned cash], 
		[December_loans_bursary_for_area_costs_balancing_earned_cash] AS [December loans bursary for area costs balancing earned cash], 
		[December_loans_bursary_total_earned_cash] AS [December loans bursary total earned cash], 
		[January_ALB_Code_used] AS [January ALB code used], 
		[January_ALB_support_payment_earned_cash] AS [January ALB support payment earned cash], 
		[January_loans_bursary_for_area_costs_on_programme_earned_cash] AS [January loans bursary for area costs on programme earned cash], 
		[January_loans_bursary_for_area_costs_balancing_earned_cash] AS [January loans bursary for area costs balancing earned cash], 
		[January_loans_bursary_total_earned_cash] AS [January loans bursary total earned cash], 
		[February_ALB_Code_used] AS [February ALB code used], 
		[February_ALB_support_payment_earned_cash] AS [February ALB support payment earned cash], 
		[February_loans_bursary_for_area_costs_on_programme_earned_cash] AS [February loans bursary for area costs on programme earned cash], 
		[February_loans_bursary_for_area_costs_balancing_earned_cash] AS [February loans bursary for area costs balancing earned cash], 
		[February_loans_bursary_total_earned_cash] AS [February loans bursary total earned cash], 
		[March_ALB_Code_used] AS [March ALB code used], 
		[March_ALB_support_payment_earned_cash] AS [March ALB support payment earned cash], 
		[March_loans_bursary_for_area_costs_on_programme_earned_cash] AS [March loans bursary for area costs on programme earned cash], 
		[March_loans_bursary_for_area_costs_balancing_earned_cash] AS [March loans bursary for area costs balancing earned cash], 
		[March_loans_bursary_total_earned_cash] AS [March loans bursary total earned cash], 
		[April_ALB_Code_used] AS [April ALB code used], 
		[April_ALB_support_payment_earned_cash] AS [April ALB support payment earned cash], 
		[April_loans_bursary_for_area_costs_on_programme_earned_cash] AS [April loans bursary for area costs on programme earned cash], 
		[April_loans_bursary_for_area_costs_balancing_earned_cash] AS [April loans bursary for area costs balancing earned cash], 
		[April_loans_bursary_total_earned_cash] AS [April loans bursary total earned cash], 
		[May_ALB_Code_used] AS [May ALB code used], 
		[May_ALB_support_payment_earned_cash] AS [May ALB support payment earned cash], 
		[May_loans_bursary_for_area_costs_on_programme_earned_cash] AS [May loans bursary for area costs on programme earned cash], 
		[May_loans_bursary_for_area_costs_balancing_earned_cash] AS [May loans bursary for area costs balancing earned cash], 
		[May_loans_bursary_total_earned_cash] AS [May loans bursary total earned cash], 
		[June_ALB_Code_used] AS [June ALB code used], 
		[June_ALB_support_payment_earned_cash] AS [June ALB support payment earned cash], 
		[June_loans_bursary_for_area_costs_on_programme_earned_cash] AS [June loans bursary for area costs on programme earned cash], 
		[June_loans_bursary_for_area_costs_balancing_earned_cash] AS [June loans bursary for area costs balancing earned cash], 
		[June_loans_bursary_total_earned_cash] AS [June loans bursary total earned cash], 
		[July_ALB_Code_used] AS [July ALB code used], 
		[July_ALB_support_payment_earned_cash] AS [July ALB support payment earned cash], 
		[July_loans_bursary_for_area_costs_on_programme_earned_cash] AS [July loans bursary for area costs on programme earned cash], 
		[July_loans_bursary_for_area_costs_balancing_earned_cash] AS [July loans bursary for area costs balancing earned cash], 
		[July_loans_bursary_total_earned_cash] AS [July loans bursary total earned cash], 
		[Total_ALB_support_payment_earned_cash] AS [Total ALB support payment earned cash], 
		[Total_loans_bursary_for_area_costs_on_programme_earned_cash] AS [Total loans bursary for area costs on programme earned cash], 
		[Total_loans_bursary_for_area_costs_balancing_earned_cash] AS [Total loans bursary for area costs balancing earned cash], 
		[Total_earned_cash] AS [Total earned cash], 
		[OFFICIAL_SENSITIVE] AS [OFFICIAL - SENSITIVE]
	FROM (
		SELECT 
			ROW_NUMBER() OVER(ORDER BY [Learner_reference_number], [Learning_aim_reference]) AS [RowNumber], 
			[Learner_reference_number],
			[Unique_learner_number],
			[Date_of_birth],
			[PMUKPRN],
			[Provider_specified_learner_monitoring_A],
			[Provider_specified_learner_monitoring_B],
			[Aim_sequence_number],
			[Learning_aim_reference],
			[Learning_aim_title],
			[Software_supplier_aim_identifier],
			[Applicable_funding_rate],
			[Applicable_programme_weighting],
			[Notional_NVQ_level],
			[Tier_2_sector_subject_area],
			[Aim_type],
			[Funding_model],
			[Funding_adjustment_for_prior_learning],
			[Other_funding_adjustment],
			[Original_learning_start_date],
			[Learning_start_date],
			[Learning_planned_end_date],
			[Completion_status],
			[Learning_actual_end_date],
			[Outcome],
			[Learning_delivery_funding_and_monitoring_type_Advanced_Learner_Loans_indicator],
			[Learning_delivery_funding_and_monitoring_type_Advanced_Learner_Loans_Bursary_funding],
			[Learning_delivery_funding_and_monitoring_ALB_date_applies_from],
			[Learning_delivery_funding_and_monitoring_ALB_date_applies_to],
			[Learning_delivery_funding_and_monitoring_type_learning_delivery_monitoring_A],
			[Learning_delivery_funding_and_monitoring_type_learning_delivery_monitoring_B],
			[Learning_delivery_funding_and_monitoring_type_learning_delivery_monitoring_C],
			[Learning_delivery_funding_and_monitoring_type_learning_delivery_monitoring_D],
			[Provider_specified_delivery_monitoring_A],
			[Provider_specified_delivery_monitoring_B],
			[Provider_specified_delivery_monitoring_C],
			[Provider_specified_delivery_monitoring_D],
			[Sub_contracted_or_partnership_UKPRN],
			[Delivery_location_postcode],
			[Area_uplift],
			[Funding_line_type],
			[First_liability_date],
			[Planned_number_of_instalments],
			[Date_used_for_factor_lookups],
			[August_ALB_code_used],
			[August_ALB_support_payment_earned_cash],
			[August_loans_bursary_for_area_costs_on_programme_earned_cash],
			[August_loans_bursary_for_area_costs_balancing_earned_cash],
			[August_loans_bursary_total_earned_cash],
			[September_ALB_Code_used],
			[September_ALB_support_payment_earned_cash],
			[September_loans_bursary_for_area_costs_on_programme_earned_cash],
			[September_loans_bursary_for_area_costs_balancing_earned_cash],
			[September_loans_bursary_total_earned_cash],
			[October_ALB_Code_used],
			[October_ALB_support_payment_earned_cash],
			[October_loans_bursary_for_area_costs_on_programme_earned_cash],
			[October_loans_bursary_for_area_costs_balancing_earned_cash],
			[October_loans_bursary_total_earned_cash],
			[November_ALB_Code_used],
			[November_ALB_support_payment_earned_cash],
			[November_loans_bursary_for_area_costs_on_programme_earned_cash],
			[November_loans_bursary_for_area_costs_balancing_earned_cash],
			[November_loans_bursary_total_earned_cash],
			[December_ALB_Code_used],
			[December_ALB_support_payment_earned_cash],
			[December_loans_bursary_for_area_costs_on_programme_earned_cash],
			[December_loans_bursary_for_area_costs_balancing_earned_cash],
			[December_loans_bursary_total_earned_cash],
			[January_ALB_Code_used],
			[January_ALB_support_payment_earned_cash],
			[January_loans_bursary_for_area_costs_on_programme_earned_cash],
			[January_loans_bursary_for_area_costs_balancing_earned_cash],
			[January_loans_bursary_total_earned_cash],
			[February_ALB_Code_used],
			[February_ALB_support_payment_earned_cash],
			[February_loans_bursary_for_area_costs_on_programme_earned_cash],
			[February_loans_bursary_for_area_costs_balancing_earned_cash],
			[February_loans_bursary_total_earned_cash],
			[March_ALB_Code_used],
			[March_ALB_support_payment_earned_cash],
			[March_loans_bursary_for_area_costs_on_programme_earned_cash],
			[March_loans_bursary_for_area_costs_balancing_earned_cash],
			[March_loans_bursary_total_earned_cash],
			[April_ALB_Code_used],
			[April_ALB_support_payment_earned_cash],
			[April_loans_bursary_for_area_costs_on_programme_earned_cash],
			[April_loans_bursary_for_area_costs_balancing_earned_cash],
			[April_loans_bursary_total_earned_cash],
			[May_ALB_Code_used],
			[May_ALB_support_payment_earned_cash],
			[May_loans_bursary_for_area_costs_on_programme_earned_cash],
			[May_loans_bursary_for_area_costs_balancing_earned_cash],
			[May_loans_bursary_total_earned_cash],
			[June_ALB_Code_used],
			[June_ALB_support_payment_earned_cash],
			[June_loans_bursary_for_area_costs_on_programme_earned_cash],
			[June_loans_bursary_for_area_costs_balancing_earned_cash],
			[June_loans_bursary_total_earned_cash],
			[July_ALB_Code_used],
			[July_ALB_support_payment_earned_cash],
			[July_loans_bursary_for_area_costs_on_programme_earned_cash],
			[July_loans_bursary_for_area_costs_balancing_earned_cash],
			[July_loans_bursary_total_earned_cash],
			[Total_ALB_support_payment_earned_cash],
			[Total_loans_bursary_for_area_costs_on_programme_earned_cash],
			[Total_loans_bursary_for_area_costs_balancing_earned_cash],
			[Total_earned_cash],
			[OFFICIAL_SENSITIVE]
		FROM [Report].[ALLBOccupancyReportData]
	) AS OUTER_SELECT
	WHERE RowNumber BETWEEN((@Page - 1) * @PageSize) AND (@Page * @PageSize - 1)
	ORDER BY [Learner reference number], [Learning aim reference]
END

GO