IF NOT EXISTS(SELECT [schema_id] FROM sys.schemas WHERE [name]='Report')
BEGIN
	EXEC('CREATE SCHEMA Report')
END
GO

-----------------------------------------------------------------------------------------------------------------------------------------------
--Apprenticeships Indicative Earnings Report 2016/17
-----------------------------------------------------------------------------------------------------------------------------------------------
IF EXISTS(SELECT [object_id] FROM sys.tables WHERE [name]='AppsIndicativeEarningsReport' AND [schema_id] = SCHEMA_ID('Report'))
BEGIN
	DROP TABLE Report.AppsIndicativeEarningsReport
END
GO

CREATE TABLE [Report].[AppsIndicativeEarningsReport](	
	[RowNumber] INT NOT NULL,
	[Learner reference number] [varchar](12) NOT NULL,
	[Unique learner number] [bigint] NOT NULL,
	[Date of birth] [date] NULL,
	[Postcode prior to enrolment]  [varchar](8) NULL,
	[Provider specified learner monitoring (A)] [varchar](20) NULL,
	[Provider specified learner monitoring (B)] [varchar](20) NULL,

	[Aim sequence number] [int] NOT NULL,
	[Learning aim reference] [varchar](8)  NULL,
	[Learning aim title] [varchar](254) NULL,
	[Software supplier aim identifier] [varchar](36) NULL,
	[LARS 16-18 additional payments - employer] varchar(20) NULL,
	[LARS 16-18 additional payments - provider]  varchar(20) NULL,
	[LARS 16-18 framework uplift] varchar(20) NULL,
	[Notional NVQ level] [varchar](5) NULL,
	[Standard notional end level] varchar(20) null,
	[Tier 2 sector subject area] decimal(5, 2) NULL,

	[Programme type] [int] NULL,
	[Standard code] [bigint] NULL,
	[Framework code]  [int] NULL,
	[Apprenticeship pathway] [int] NULL,
	[Aim type] [int]  NULL,
	[Common component code] [int] NULL,
	[Funding model] [int]  NULL,
	[Original learning start date] [date] NULL,
	[Learning start date] [date]  NULL,
	[Learning planned end date] [date]  NULL,
	[Completion status] [int] NULL,

	[Learning actual end date]  [date] NULL,
	[Outcome] [int] NULL,
	[Learning delivery funding and monitoring type – source of funding]  [varchar](5) NULL,
	[Learning delivery funding and monitoring type – learning support funding (highest applicable)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - LSF date applies from (earliest)] [date] NULL,
	[Learning delivery funding and monitoring type - LSF date applies to (latest)] [date] NULL,
	[Learning delivery funding and monitoring type – learning delivery monitoring (A)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type – learning delivery monitoring (B)]  [varchar](5) NULL,
	[Learning delivery funding and monitoring type – learning delivery monitoring (C)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type – learning delivery monitoring (D)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type – restart indicator] [varchar](5) NULL,
	[Provider specified delivery monitoring (A)] [varchar](20) NULL,
	[Provider specified delivery monitoring (B)] [varchar](20) NULL,
	[Provider specified delivery monitoring (C)] [varchar](20) NULL,
	[Provider specified delivery monitoring (D)] [varchar](20) NULL,
	[Endpoint assessment organisation] [varchar](7) NULL,
    [Planned number of on programme instalments for aim] int NULL,
    [Sub contracted or partnership UKPRN] int NULL,
    [Delivery location postcode] varchar(8) NULL,
    [Employer identifier] int NULL,  
    [Employment status] int NULL,
    [Employment status date] Date NULL,
    [Employment status monitoring - small employer] int NULL,
	[Price episode start date]  Date NULL,
	[Price episode actual end date] Date NULL,
	[Funding line type] varchar(100) NULL,
	[Total price applicable to this episode] Decimal(15,5) NULL,
	[Funding band upper limit] Decimal(15,5) NULL,
	[Price amount above funding band limit] Decimal(15,5) NULL,
	[Price amount remaining (with upper limit applied) at start of this episode] Decimal(15,5) NULL,
	[Completion element (potential or actual earned cash)] [decimal](15, 5)  NULL,
	[Total employer contribution collected (PMR) in previous funding years] [decimal](15, 5)  NULL,
	[Total employer contribution collected (PMR) in this funding year] [decimal](15, 5)  NULL,
	[Learning delivery funding and monitoring type – apprenticeship contract type]  [varchar](5) NULL,
	[Learning delivery funding and monitoring type – ACT date applies from]  [date] NULL,
	[Learning delivery funding and monitoring type – ACT date applies to] [date] NULL,
	

	[August on programme earned cash] [decimal](15, 5) NULL,
	[August balancing payment earned cash] [decimal](15, 5) NULL,
	[August aim completion earned cash] [decimal](15, 5) NULL,
	[August total training and assessment earned] [decimal](15, 5) NULL,
	[August learning support earned cash]  decimal(15,5) null,
	[August English and Maths on programme earned cash]  decimal(15,5) null,
    [August English and Maths balancing payment earned cash]  decimal(15,5) null,
	[August disadvantage earned cash]  decimal(15,5) null,
	[August 16-18 additional payments for employers]  decimal(15,5) null,
	[August 16-18 additional payments for providers]  decimal(15,5) null,
	[August 16-18 framework uplift on programme payment] decimal(15,5) null,
	[August 16-18 framework uplift balancing payment] decimal(15,5) null,
	[August 16-18 framework uplift completion payment] decimal(15,5) null,
	

	[September on programme earned cash] [decimal](15, 5) NULL,
	[September balancing payment earned cash] [decimal](15, 5) NULL,
	[September aim completion earned cash] [decimal](15, 5) NULL,
	[September total training and assessment earned] [decimal](15, 5) NULL,
	[September learning support earned cash]  decimal(15,5) null,
	[September English and Maths on programme earned cash]  decimal(15,5) null,
    [September English and Maths balancing payment earned cash]  decimal(15,5) null,
	[September disadvantage earned cash]  decimal(15,5) null,
	[September 16-18 additional payments for employers]  decimal(15,5) null,
	[September 16-18 additional payments for providers]  decimal(15,5) null,
	[September 16-18 framework uplift on programme payment] decimal(15,5) null,
	[September 16-18 framework uplift balancing payment] decimal(15,5) null,
	[September 16-18 framework uplift completion payment] decimal(15,5) null,

	[October on programme earned cash] [decimal](15, 5) NULL,
	[October balancing payment earned cash] [decimal](15, 5) NULL,
	[October aim completion earned cash] [decimal](15, 5) NULL,
	[October total training and assessment earned] [decimal](15, 5) NULL,
	[October learning support earned cash]  decimal(15,5) null,
	[October English and Maths on programme earned cash]  decimal(15,5) null,
    [October English and Maths balancing payment earned cash]  decimal(15,5) null,
	[October disadvantage earned cash]  decimal(15,5) null,
	[October 16-18 additional payments for employers]  decimal(15,5) null,
	[October 16-18 additional payments for providers]  decimal(15,5) null,
	[October 16-18 framework uplift on programme payment] decimal(15,5) null,
	[October 16-18 framework uplift balancing payment] decimal(15,5) null,
	[October 16-18 framework uplift completion payment] decimal(15,5) null,

	[November on programme earned cash] [decimal](15, 5) NULL,
	[November balancing payment earned cash] [decimal](15, 5) NULL,
	[November aim completion earned cash] [decimal](15, 5) NULL,
	[November total training and assessment earned] [decimal](15, 5) NULL,
	[November learning support earned cash]  decimal(15,5) null,
	[November English and Maths on programme earned cash]  decimal(15,5) null,
    [November English and Maths balancing payment earned cash]  decimal(15,5) null,
	[November disadvantage earned cash]  decimal(15,5) null,
	[November 16-18 additional payments for employers]  decimal(15,5) null,
	[November 16-18 additional payments for providers]  decimal(15,5) null,
	[November 16-18 framework uplift on programme payment] decimal(15,5) null,
	[November 16-18 framework uplift balancing payment] decimal(15,5) null,
	[November 16-18 framework uplift completion payment] decimal(15,5) null,

	[December on programme earned cash] [decimal](15, 5) NULL,
	[December balancing payment earned cash] [decimal](15, 5) NULL,
	[December aim completion earned cash] [decimal](15, 5) NULL,
	[December total training and assessment earned] [decimal](15, 5) NULL,
	[December learning support earned cash]  decimal(15,5) null,
	[December English and Maths on programme earned cash]  decimal(15,5) null,
    [December English and Maths balancing payment earned cash]  decimal(15,5) null,
	[December disadvantage earned cash]  decimal(15,5) null,
	[December 16-18 additional payments for employers]  decimal(15,5) null,
	[December 16-18 additional payments for providers]  decimal(15,5) null,
	[December 16-18 framework uplift on programme payment] decimal(15,5) null,
	[December 16-18 framework uplift balancing payment] decimal(15,5) null,
	[December 16-18 framework uplift completion payment] decimal(15,5) null,

	[January on programme earned cash] [decimal](15, 5) NULL,
	[January balancing payment earned cash] [decimal](15, 5) NULL,
	[January aim completion earned cash] [decimal](15, 5) NULL,
	[January total training and assessment earned] [decimal](15, 5) NULL,
	[January learning support earned cash]  decimal(15,5) null,
	[January English and Maths on programme earned cash]  decimal(15,5) null,
    [January English and Maths balancing payment earned cash]  decimal(15,5) null,
	[January disadvantage earned cash]  decimal(15,5) null,
	[January 16-18 additional payments for employers]  decimal(15,5) null,
	[January 16-18 additional payments for providers]  decimal(15,5) null,
	[January 16-18 framework uplift on programme payment] decimal(15,5) null,
	[January 16-18 framework uplift balancing payment] decimal(15,5) null,
	[January 16-18 framework uplift completion payment] decimal(15,5) null,

	[February on programme earned cash] [decimal](15, 5) NULL,
	[February balancing payment earned cash] [decimal](15, 5) NULL,
	[February aim completion earned cash] [decimal](15, 5) NULL,
	[February total training and assessment earned] [decimal](15, 5) NULL,
	[February learning support earned cash]  decimal(15,5) null,
	[February English and Maths on programme earned cash]  decimal(15,5) null,
    [February English and Maths balancing payment earned cash]  decimal(15,5) null,
	[February disadvantage earned cash]  decimal(15,5) null,
	[February 16-18 additional payments for employers]  decimal(15,5) null,
	[February 16-18 additional payments for providers]  decimal(15,5) null,
	[February 16-18 framework uplift on programme payment] decimal(15,5) null,
	[February 16-18 framework uplift balancing payment] decimal(15,5) null,
	[February 16-18 framework uplift completion payment] decimal(15,5) null,

	[March on programme earned cash] [decimal](15, 5) NULL,
	[March balancing payment earned cash] [decimal](15, 5) NULL,
	[March aim completion earned cash] [decimal](15, 5) NULL,
	[March total training and assessment earned] [decimal](15, 5) NULL,
	[March learning support earned cash]  decimal(15,5) null,
	[March English and Maths on programme earned cash]  decimal(15,5) null,
    [March English and Maths balancing payment earned cash]  decimal(15,5) null,
	[March disadvantage earned cash]  decimal(15,5) null,
	[March 16-18 additional payments for employers]  decimal(15,5) null,
	[March 16-18 additional payments for providers]  decimal(15,5) null,
	[March 16-18 framework uplift on programme payment] decimal(15,5) null,
	[March 16-18 framework uplift balancing payment] decimal(15,5) null,
	[March 16-18 framework uplift completion payment] decimal(15,5) null,

	[April on programme earned cash] [decimal](15, 5) NULL,
	[April balancing payment earned cash] [decimal](15, 5) NULL,
	[April aim completion earned cash] [decimal](15, 5) NULL,
	[April total training and assessment earned] [decimal](15, 5) NULL,
	[April learning support earned cash]  decimal(15,5) null,
	[April English and Maths on programme earned cash]  decimal(15,5) null,
    [April English and Maths balancing payment earned cash]  decimal(15,5) null,
	[April disadvantage earned cash]  decimal(15,5) null,
	[April 16-18 additional payments for employers]  decimal(15,5) null,
	[April 16-18 additional payments for providers]  decimal(15,5) null,
	[April 16-18 framework uplift on programme payment] decimal(15,5) null,
	[April 16-18 framework uplift balancing payment] decimal(15,5) null,
	[April 16-18 framework uplift completion payment] decimal(15,5) null,

	[May on programme earned cash] [decimal](15, 5) NULL,
	[May balancing payment earned cash] [decimal](15, 5) NULL,
	[May aim completion earned cash] [decimal](15, 5) NULL,
	[May total training and assessment earned] [decimal](15, 5) NULL,
	[May learning support earned cash]  decimal(15,5) null,
	[May English and Maths on programme earned cash]  decimal(15,5) null,
    [May English and Maths balancing payment earned cash]  decimal(15,5) null,
	[May disadvantage earned cash]  decimal(15,5) null,
	[May 16-18 additional payments for employers]  decimal(15,5) null,
	[May 16-18 additional payments for providers]  decimal(15,5) null,
	[May 16-18 framework uplift on programme payment] decimal(15,5) null,
	[May 16-18 framework uplift balancing payment] decimal(15,5) null,
	[May 16-18 framework uplift completion payment] decimal(15,5) null,
	
	[June on programme earned cash] [decimal](15, 5) NULL,
	[June balancing payment earned cash] [decimal](15, 5) NULL,
	[June aim completion earned cash] [decimal](15, 5) NULL,
	[June total training and assessment earned] [decimal](15, 5) NULL,
	[June learning support earned cash]  decimal(15,5) null,
	[June English and Maths on programme earned cash]  decimal(15,5) null,
    [June English and Maths balancing payment earned cash]  decimal(15,5) null,
	[June disadvantage earned cash]  decimal(15,5) null,
	[June 16-18 additional payments for employers]  decimal(15,5) null,
	[June 16-18 additional payments for providers]  decimal(15,5) null,
	[June 16-18 framework uplift on programme payment] decimal(15,5) null,
	[June 16-18 framework uplift balancing payment] decimal(15,5) null,
	[June 16-18 framework uplift completion payment] decimal(15,5) null,
	
	[July on programme earned cash] [decimal](15, 5) NULL,
	[July balancing payment earned cash] [decimal](15, 5) NULL,
	[July aim completion earned cash] [decimal](15, 5) NULL,
	[July total training and assessment earned] [decimal](15, 5) NULL,
	[July learning support earned cash]  decimal(15,5) null,
	[July English and Maths on programme earned cash]  decimal(15,5) null,
    [July English and Maths balancing payment earned cash]  decimal(15,5) null,
	[July disadvantage earned cash]  decimal(15,5) null,
	[July 16-18 additional payments for employers]  decimal(15,5) null,
	[July 16-18 additional payments for providers]  decimal(15,5) null,
	[July 16-18 framework uplift on programme payment] decimal(15,5) null,
	[July 16-18 framework uplift balancing payment] decimal(15,5) null,
	[July 16-18 framework uplift completion payment] decimal(15,5) null,

	[Total on programme earned cash]  decimal(15,5) null,
	[Total balancing payment earned cash]  decimal(15,5) null,
	[Total aim completion earned cash]  decimal(15,5) null,
	[Total training and assessment earned]  decimal(15,5) null,
	[Total learning support earned cash]  decimal(15,5) null,	
	[Total English and Maths on programme earned cash] decimal(15,5) null,
	[Total English and Maths balancing payment earned cash] decimal(15,5) null,
	[Total disadvantage earned cash]  decimal(15,5) null,
	[Total 16-18 additional payments for employers]  decimal(15,5) null,
	[Total 16-18 additional payments for providers]  decimal(15,5) null,
	[Total 16-18 framework uplift on programme payment] decimal(15,5) null,
	[Total 16-18 framework uplift balancing payment] decimal(15,5) null,
	[Total 16-18 framework uplift completion payment] decimal(15,5) null,
	[OFFICIAL - SENSITIVE] nvarchar(20) null
)
