
IF OBJECT_ID('Report.TrailblazerApprenticeshipsOccupancyReport') IS NOT NULL
BEGIN
    DROP TABLE  [Report].[TrailblazerApprenticeshipsOccupancyReport]
END;

CREATE TABLE [Report].[TrailblazerApprenticeshipsOccupancyReport](
	[RowNumber] INT NOT NULL,
	[Learner reference number] [varchar](12) NULL,
	[Unique learner number] [bigint] NULL,
	[Date of birth] [varchar](10) NULL,
	[Pre-merger UKPRN] [int] null,
	[Provider specified learner monitoring (A)] [varchar](20) NULL,
	[Provider specified learner monitoring (B)] [varchar](20) NULL,
	[Aim sequence number] [int] NOT NULL,
	[Learning aim reference] [varchar](8) NOT NULL,
	[Learning aim title] [varchar](254) NULL,
	[Software supplier aim identifier] [varchar](36) NULL,
	[Notional NVQ level] [varchar](5) NULL,
	[Aim type] [int] NOT NULL,
	[Apprenticeship standard code] [int] null,
	[Funding model] [int] NOT NULL,
	[Funding adjustment for prior learning] [int] NULL,
	[Other funding adjustment] [int] NULL,
	[Original learning start date] [date] NULL,
	[Learning start date] [date] NOT NULL,
	[Learning planned end date] [date] NOT NULL,
	[Completion status] [int] NULL,
	[Learning actual end date] [date] NULL,
	[Outcome] [int] NULL,
	[Achievement date] [date] NULL,
	[Learning delivery funding and monitoring type - source of funding] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - eligibility for enhanced apprenticeship funding] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - learning support funding (highest applicable)] [varchar](5) NULL,
	[Learning delivery funding and monitoring - LSF date applies from (earliest)] [date] NULL,
	[Learning delivery funding and monitoring - LSF date applies to (latest)] [date] NULL,
	[Learning delivery funding and monitoring type - learning delivery monitoring (A)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - learning delivery monitoring (B)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - learning delivery monitoring (C)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - learning delivery monitoring (D)] [varchar](5) NULL,
	[Learning delivery funding and monitoring type - restart indicator] [varchar](5) NULL,
	[Provider specified delivery monitoring (A)] [varchar](20) NULL,
	[Provider specified delivery monitoring (B)] [varchar](20) NULL,
	[Provider specified delivery monitoring (C)] [varchar](20) NULL,
	[Provider specified delivery monitoring (D)] [varchar](20) NULL,
	[End point assessment organisation] [varchar](7) null,
	[Sub contracted or partnership UKPRN] [int] NULL,
	[Delivery location postcode] [varchar](8) NULL,
	[LARS maximum core government contribution] [decimal](10, 5) NULL,
	[LARS small employer incentive] [decimal](10, 5) NULL,
	[LARS 16-18 year-old apprentice incentive] [decimal](10, 5) NULL,
	[LARS achievement incentive] [decimal](10, 5) NULL,
	[Applicable funding value date] [date] NULL,
	[Funding line type] [varchar](100) NULL,
	[Employer identifier on first day of standard] [int] NULL,
	[Employer identifier on small employer threshold date] [int] NULL,
	[Employer identifier on first 16-18 threshold date] [int] NULL,
	[Employer identifier on second 16-18 threshold date] [int] NULL,
	[Employer identifier on achievement date] [int] NULL,
	[Start indicator for maths, English and learning support] [bit] NULL,
	[Age at start of standard] [int] NULL,
	[Eligible for 16-18 year-old apprentice incentive] [bit] NULL,
	[Eligible for small employer incentive] [bit] NULL,
	[Applicable achievement date] [date] NULL,
	[Latest total negotiated price (TNP) 1] [int] NULL,
	[Latest total negotiated price (TNP) 2] [int] NULL,
	[Sum of PMRs before this funding year] [int] NULL,
	[Sum of August payment records (PMRs)] [int] NULL,
	[August core government contribution] [decimal](15, 5) NULL,
	[August maths and English on-programme earned cash] [decimal](15, 5) NULL,
	[August maths and English balancing earned cash] [decimal](15, 5) NULL,
	[August learning support earned cash] [decimal](15, 5) NULL,
	[August small employer incentive] [decimal](15, 5) NULL,
	[August 16-18 year-old apprentice incentive] [decimal](15, 5) NULL,
	[August achievement incentive] [decimal](15, 5) NULL,
	[Sum of September payment records (PMRs)] [int] NULL,
	[September core government contribution] [decimal](15, 5) NULL,
	[September maths and English on-programme earned cash] [decimal](15, 5) NULL,
	[September maths and English balancing earned cash] [decimal](15, 5) NULL,
	[September learning support earned cash] [decimal](15, 5) NULL,
	[September small employer incentive] [decimal](15, 5) NULL,
	[September 16-18 year-old apprentice incentive] [decimal](15, 5) NULL,
	[September achievement incentive] [decimal](15, 5) NULL,
	[Sum of October payment records (PMRs)] [int] NULL,
	[October core government contribution] [decimal](15, 5) NULL,
	[October maths and English on-programme earned cash] [decimal](15, 5) NULL,
	[October maths and English balancing earned cash] [decimal](15, 5) NULL,
	[October learning support earned cash] [decimal](15, 5) NULL,
	[October small employer incentive] [decimal](15, 5) NULL,
	[October 16-18 year-old apprentice incentive] [decimal](15, 5) NULL,
	[October achievement incentive] [decimal](15, 5) NULL,
	[Sum of November payment records (PMRs)] [int] NULL,
	[November core government contribution] [decimal](15, 5) NULL,
	[November maths and English on-programme earned cash] [decimal](15, 5) NULL,
	[November maths and English balancing earned cash] [decimal](15, 5) NULL,
	[November learning support earned cash] [decimal](15, 5) NULL,
	[November small employer incentive] [decimal](15, 5) NULL,
	[November 16-18 year-old apprentice incentive] [decimal](15, 5) NULL,
	[November achievement incentive] [decimal](15, 5) NULL,
	[Sum of December payment records (PMRs)] [int] NULL,
	[December core government contribution] [decimal](15, 5) NULL,
	[December maths and English on-programme earned cash] [decimal](15, 5) NULL,
	[December maths and English balancing earned cash] [decimal](15, 5) NULL,
	[December learning support earned cash] [decimal](15, 5) NULL,
	[December small employer incentive] [decimal](15, 5) NULL,
	[December 16-18 year-old apprentice incentive] [decimal](15, 5) NULL,
	[December achievement incentive] [decimal](15, 5) NULL,
	[Sum of January payment records (PMRs)] [int] NULL,
	[January core government contribution] [decimal](15, 5) NULL,
	[January maths and English on-programme earned cash] [decimal](15, 5) NULL,
	[January maths and English balancing earned cash] [decimal](15, 5) NULL,
	[January learning support earned cash] [decimal](15, 5) NULL,
	[January small employer incentive] [decimal](15, 5) NULL,
	[January 16-18 year-old apprentice incentive] [decimal](15, 5) NULL,
	[January achievement incentive] [decimal](15, 5) NULL,
	[Sum of February payment records (PMRs)] [int] NULL,
	[February core government contribution] [decimal](15, 5) NULL,
	[February maths and English on-programme earned cash] [decimal](15, 5) NULL,
	[February maths and English balancing earned cash] [decimal](15, 5) NULL,
	[February learning support earned cash] [decimal](15, 5) NULL,
	[February small employer incentive] [decimal](15, 5) NULL,
	[February 16-18 year-old apprentice incentive] [decimal](15, 5) NULL,
	[February achievement incentive] [decimal](15, 5) NULL,
	[Sum of March payment records (PMRs)] [int] NULL,
	[March core government contribution] [decimal](15, 5) NULL,
	[March maths and English on-programme earned cash] [decimal](15, 5) NULL,
	[March maths and English balancing earned cash] [decimal](15, 5) NULL,
	[March learning support earned cash] [decimal](15, 5) NULL,
	[March small employer incentive] [decimal](15, 5) NULL,
	[March 16-18 year-old apprentice incentive] [decimal](15, 5) NULL,
	[March achievement incentive] [decimal](15, 5) NULL,
	[Sum of April payment records (PMRs)] [int] NULL,
	[April core government contribution] [decimal](15, 5) NULL,
	[April maths and English on-programme earned cash] [decimal](15, 5) NULL,
	[April maths and English balancing earned cash] [decimal](15, 5) NULL,
	[April learning support earned cash] [decimal](15, 5) NULL,
	[April small employer incentive] [decimal](15, 5) NULL,
	[April 16-18 year-old apprentice incentive] [decimal](15, 5) NULL,
	[April achievement incentive] [decimal](15, 5) NULL,
	[Sum of May payment records (PMRs)] [int] NULL,
	[May core government contribution] [decimal](15, 5) NULL,
	[May maths and English on-programme earned cash] [decimal](15, 5) NULL,
	[May maths and English balancing earned cash] [decimal](15, 5) NULL,
	[May learning support earned cash] [decimal](15, 5) NULL,
	[May small employer incentive] [decimal](15, 5) NULL,
	[May 16-18 year-old apprentice incentive] [decimal](15, 5) NULL,
	[May achievement incentive] [decimal](15, 5) NULL,
	[Sum of June payment records (PMRs)] [int] NULL,
	[June core government contribution] [decimal](15, 5) NULL,
	[June maths and English on-programme earned cash] [decimal](15, 5) NULL,
	[June maths and English balancing earned cash] [decimal](15, 5) NULL,
	[June learning support earned cash] [decimal](15, 5) NULL,
	[June small employer incentive] [decimal](15, 5) NULL,
	[June 16-18 year-old apprentice incentive] [decimal](15, 5) NULL,
	[June achievement incentive] [decimal](15, 5) NULL,
	[Sum of July payment records (PMRs)] [int] NULL,
	[July core government contribution] [decimal](15, 5) NULL,
	[July maths and English on-programme earned cash] [decimal](15, 5) NULL,
	[July maths and English balancing earned cash] [decimal](15, 5) NULL,
	[July learning support earned cash] [decimal](15, 5) NULL,
	[July small employer incentive] [decimal](15, 5) NULL,
	[July 16-18 year-old apprentice incentive] [decimal](15, 5) NULL,
	[July achievement incentive] [decimal](15, 5) NULL,
	[Total payment records (PMRs) for this funding year] [int] NULL,
	[Total core government contribution] [decimal](26, 5) NULL,
	[Total maths and English on-programme earned cash] [decimal](26, 5) NULL,
	[Total maths and English balancing earned cash] [decimal](26, 5) NULL,
	[Total learning support earned cash] [decimal](26, 5) NULL,
	[Total small employer incentive] [decimal](26, 5) NULL,
	[Total 16-18 year-old apprentice incentive] [decimal](26, 5) NULL,
	[Total achievement incentive] [decimal](26, 5) NULL,
	[OFFICIAL - SENSITIVE] [varchar](20) NULL
)

GO

SET ANSI_PADDING OFF
GO


