//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ESFA.Common.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ESFA.Common.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User cancelled operation.
        /// </summary>
        internal static string CanceledOperation {
            get {
                return ResourceManager.GetString("CanceledOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencing file load @ &quot;{0}&quot;.
        /// </summary>
        internal static string CommencingLoadFormat {
            get {
                return ResourceManager.GetString("CommencingLoadFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencing run @ &quot;{0}&quot;.
        /// </summary>
        internal static string CommencingRunFormat {
            get {
                return ResourceManager.GetString("CommencingRunFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencing log save @ &quot;{0}&quot;.
        /// </summary>
        internal static string CommencingSaveFormat {
            get {
                return ResourceManager.GetString("CommencingSaveFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commencing input data load @ &quot;{0}&quot;.
        /// </summary>
        internal static string CommencingSelectFormat {
            get {
                return ResourceManager.GetString("CommencingSelectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to completed....
        /// </summary>
        internal static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded and ready for use....
        /// </summary>
        internal static string ConsoleDefault {
            get {
                return ResourceManager.GetString("ConsoleDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialise a null or empty item.
        /// </summary>
        internal static string GuardCannotDeserialise {
            get {
                return ResourceManager.GetString("GuardCannotDeserialise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File missing: &quot;{0}&quot;.
        /// </summary>
        internal static string GuardFileMissingFormat {
            get {
                return ResourceManager.GetString("GuardFileMissingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file loading complete.
        /// </summary>
        internal static string InputFileLoadingComplete {
            get {
                return ResourceManager.GetString("InputFileLoadingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input file read complete.
        /// </summary>
        internal static string InputFileReadComplete {
            get {
                return ResourceManager.GetString("InputFileReadComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ==========================================.
        /// </summary>
        internal static string LineDivider {
            get {
                return ResourceManager.GetString("LineDivider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading &quot;{0}&quot; from disk.
        /// </summary>
        internal static string LoadingFromDiskFormat {
            get {
                return ResourceManager.GetString("LoadingFromDiskFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not yet implemented: &quot;{0}&quot;.
        /// </summary>
        internal static string NotYetImplementedFormat {
            get {
                return ResourceManager.GetString("NotYetImplementedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation failed with the following message:.
        /// </summary>
        internal static string OperationFailedWithMessage {
            get {
                return ResourceManager.GetString("OperationFailedWithMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Performing schema validation on: &quot;{0}&quot;.
        /// </summary>
        internal static string PerformingSchemaValidationOnFormat {
            get {
                return ResourceManager.GetString("PerformingSchemaValidationOnFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Writing file ({0}) to disk.
        /// </summary>
        internal static string SavingToDiskFormat {
            get {
                return ResourceManager.GetString("SavingToDiskFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation terminated due to schema invalidation.
        /// </summary>
        internal static string SchemaValidationFailed {
            get {
                return ResourceManager.GetString("SchemaValidationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Using schema file: &quot;{0}&quot;.
        /// </summary>
        internal static string UsingSchemaFileFormat {
            get {
                return ResourceManager.GetString("UsingSchemaFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation failed due to a number of errors....
        /// </summary>
        internal static string ValidationFailedDueToErrors {
            get {
                return ResourceManager.GetString("ValidationFailedDueToErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count: {0} Message: {1}.
        /// </summary>
        internal static string ValidationFailedFormat {
            get {
                return ResourceManager.GetString("ValidationFailedFormat", resourceCulture);
            }
        }
    }
}
